### ISSUE TITLE
Use cfg(target_has_atomic) instead of hard coding which targets support atomics

### ISSUE THREAD

**Issue by bjorn3** [crossbeam-rs/crossbeam#1033]
This has been stable since 1.60.0: https://github.com/rust-lang/rust/pull/93824 The hard coded list is bound to go out of sync with rustc, especially when new targets get added. As rustc itself depends on crossbeam, this means it isn't possible to build rustc for targets lacking some atomics until a new crossbeam release with those new targets. Using `cfg(target_has_atomic)` will immediately work. While the MSRV of crossbeam is lower than 1.60.0, it should be possible to use the hard coded list as fallback when the rustc version is too old for stable `cfg(target_has_atomic)`.

**Comment by bjorn3** [comment]
cc https://github.com/rust-lang/rust/pull/117170#discussion_r1373230638

**Comment by taiki-e** [comment]
> While the MSRV of crossbeam is lower than 1.60.0, it should be possible to use the hard coded list as fallback when the rustc version is too old for stable `cfg(target_has_atomic)`.

This is an approach I have previously explicitly stated I accept and would accept a PR that implements this.
https://github.com/crossbeam-rs/crossbeam/pull/937#issuecomment-1338885510

**Comment by bjorn3** [comment]
Do you know how to handle `cfg(not(crossbeam_no_atomic_cas))`? Use `cfg(target_has_atomic="ptr")`?

**Comment by taiki-e** [comment]
> Use `cfg(target_has_atomic="ptr")`?

Yes.

- `not(crossbeam_no_atomic_cas)` corresponds to `target_has_atomic = "ptr"`.
- `not(crossbeam_no_atomic_64)` (almost) corresponds to `target_has_atomic = "64"`. (To be precise, it is closer to unstable `target_has_atomic_load_store = "64"`, but currently, the only time the two would actually have different meanings is when using a custom target.)
- `not(crossbeam_no_atomic)` (almost) corresponds to unstable `target_has_atomic_load_store = "ptr"`. There is no stable alternative to this, so I think this may require continuing to use our own cfg. This cfg only affects some no-std targets.

**Comment by bjorn3** [comment]
Is adding autocfg as build dependency to the crates that don't have it yet fine?

**Comment by taiki-e** [comment]
Yeah, it's fine.

That said, given that #1015 will increase MSRV to 1.59, it is also probably actually fine to increase MSRV to 1.60 or 1.61 and remove the need for build scripts.

**Comment by bjorn3** [comment]
I think I will wait for that PR.
