### ISSUE TITLE
crossbeam-utils fails to compile on esp32* targets starting Rust 1.74

### ISSUE THREAD

**Issue by torkleyy** [crossbeam-rs/crossbeam#1048]
Emulation for 64-bit atomics was removed (https://github.com/rust-lang/rust/issues/117305, https://github.com/esp-rs/rust/pull/196), so the latest release no longer compiles.

The latest code on main does compile, because it uses the correct cfgs to check for availability of 64-bit atomics.

**Comment by taiki-e** [comment]
> The latest code on main does compile, because it uses the correct cfgs to check for availability of 64-bit atomics.

Yeah, we need to create new release.

**Comment by taiki-e** [comment]
The changes needed for the release are already in v0.8-next branch, but I have to go to work so the release will probably be this evening (in JST).

**Comment by taiki-e** [comment]
Published crossbeam-utils v0.8.17.
