### ISSUE TITLE
provide a scoped thread start taht returns result 

### ISSUE THREAD

**Issue by przygienda** [crossbeam-rs/crossbeam#1052]
following code: 

    pub fn spawn<'scope, F, T>(&'scope self, f: F) -> ScopedJoinHandle<'scope, T>
    where
        F: FnOnce(&Scope<'env>) -> T,
        F: Send + 'env,
        T: Send + 'env,
    {
        self.builder()
            .spawn(f)
            .expect("failed to spawn scoped thread")
    }

on long running applications under load we see the operating system sometimes returning "WouldBlock" and crashing the whole application (actually a thread in an application but that's about the same) 

another API is needed e.g.

safe_spawn ... Result<ScopedJoinHandle<...

I think one can force that with builder but it's simply a bad design to have excepts in the middle of infra library code

**Comment by taiki-e** [comment]
crossbeam's scope threads have been soft-deprecated in favor of the more efficient `std::thread::scope` that stabilized on Rust 1.63, as [documented](https://docs.rs/crossbeam-utils/latest/crossbeam_utils/thread/fn.scope.html), so there are no plans to accept new APIs to it.

Please consider opening an issue for `std::thread::scope` at https://github.com/rust-lang/rust.
