### ISSUE TITLE
Potential to modify the ordering for 'load' operations in the garbage module of branch 0.2.10

### ISSUE THREAD

**Issue by wang384670111** [crossbeam-rs/crossbeam#1064]
I developed a static analysis tool to detect issues related to memory ordering, thread performance, and security. During my examination of several crates, I encountered alarms triggered by the following code：
https://github.com/crossbeam-rs/crossbeam/blob/5f549d5dac8765347eba89698fa8ab1352cf0aa5/src/mem/epoch/garbage.rs#L121-L127
https://github.com/crossbeam-rs/crossbeam/blob/5f549d5dac8765347eba89698fa8ab1352cf0aa5/src/mem/epoch/garbage.rs#L133-L142

At line 126, `Release` is used to perform a successful initialization operation. However, at line 133, we should use `Acquire` to observe other modifications made to this memory address, such as the operation performed in line 126. Therefore, I believe that the `load` operation for the `head` should use 'Acquire'.

(happy to make a PR if this looks reasonable)

**Comment by tomtomjhj** [comment]
Relaxed at 133 is fine because `head` loaded from 133 is not dereferenced. The actual value to be dereferenced is acquired-swapped at 135.

Also actually the load at 124 can be relaxed (thanks to release sequence). And `.next` field can be non-atomic.


> should use Acquire to observe other modifications made to this memory address

release-acquire synchronization is about conditionally passing the knowledge about other locations, not the location that is being stored to and loaded from.

**Comment by wang384670111** [comment]
> release-acquire synchronization is about conditionally passing the knowledge about other locations, not the location that is being stored to and loaded from.
I agree. My initial thought is that the location stored by AtomicPtr is a pointer, yet the content it points to is non-atomic. Indeed, line 137 does not perform dereferencing; I was mistaken. It appears I need to revise the detection pattern.

**Comment by wang384670111** [comment]
Hm, I've updated the detection pattern, successfully eliminating the false positive. 
https://github.com/crossbeam-rs/crossbeam/blob/5f549d5dac8765347eba89698fa8ab1352cf0aa5/src/mem/epoch/garbage.rs#L124
Regarding the use of ordering, my detector can identify it as well. Here are the results. May I submit a pull request?

      {
        "AtomicCorrelationViolation": {
          "bug_kind": "AtimicCorrelationViolation",
          "possibility": "Possibly",
          "diagnosis": {
            "atomic": "/Users/wangcheng/.cargo/registry/src/index.crates.io-6f17d22bba15001f/crossbeam-0.2.12/src/mem/epoch/garbage.rs:124:34: 124:47"
          },
          "explanation": "Using an atomic operation with a stronger memory ordering than necessary can lead to unnecessary performance overhead. Using Relaxed is sufficient to ensure the correctness of the program"
        }
      },

**Comment by taiki-e** [comment]
I'm not interested in accepting an optimization patch for a 7 year old release, but I would be willing to accept a patch to the latest version.
