### ISSUE TITLE
Supporting `allocator_api`

### ISSUE THREAD

**Issue by vinaychandra** [crossbeam-rs/crossbeam#1081]
Crossbeam currently requires either `std` or `alloc`. This means using global allocators where `alloc` is needed. Are there any plans for supporting [allocator_api](https://doc.rust-lang.org/beta/unstable-book/library-features/allocator-api.html)? The library could potentially use [allocator-api2 crate](https://crates.io/crates/allocator-api2) to support these APIs in stable channel as well instead of being nightly only.

Will a contribution be accepted for such a feature?

**Comment by taiki-e** [comment]
I would like to support it once it stabilizes, but not before.

The current API is in need of rework (e.g., see https://shift.click/blog/allocator-trait-talk/), and using a crate that "copies the current implementation and makes it available in stable" does not avoid the problems.
