### ISSUE TITLE
Complexity O()

### ISSUE THREAD

**Issue by starkbamse** [crossbeam-rs/crossbeam#1099]
What is the complexity of read write operations in SkipMap and SkipSet? These are rather important metrics that should be part of the README.md imo.

**Comment by caelunshun** [comment]
`O(log n)` average, `O(n)` worst case for lookups, insertions, and deletions. I don't think the `O(n)` worst case is likely to occur typically.

**Comment by starkbamse** [comment]
> `O(log n)` average, `O(n)` worst case for lookups, insertions, and deletions. I don't think the `O(n)` worst case is likely to occur typically.

Excellent, thanks for this.
