### ISSUE TITLE
Low-level access to the epoch API

### ISSUE THREAD

**Issue by ticki** [crossbeam-rs/crossbeam#113]
I need to make use of the 0x1 pointer, which is not possible under current high-level API. I imagine similar cases exists, and exposing low-level access to the internal `crossbeam::mem::epoch` methods would suffice.

**Comment by stjepang** [comment]
Do you perhaps have a concrete use case you could point to or describe?

I do have some ideas what the API should look like, but having something more concrete to look at would greatly help in designing an appropriate API.

**Comment by ticki** [comment]
So my usecase is (was; I ended up finding another way) atomic hash maps: I need to have keys have up to 3 states. These can easily be represented as invalid pointers (0x0, 0x1, 0x2), but `epoch::Atomic<T>` only allows one nullable state.

It is possible to reimplement `epoch::Atomic<T>` this way, but it is quite inconvinient.
