### ISSUE TITLE
Non-macro biased Select?

### ISSUE THREAD

**Issue by SimonSapin** [crossbeam-rs/crossbeam#1145]
https://github.com/crossbeam-rs/crossbeam/pull/1040 added a `select_biased!` macro. Some internal functions gained an `is_biased: bool` parameter to support it, but the non-macro public API around the `Select` type does not expose this functionality at all. Some of those internal functions are only ever called with `false`. Biased functionality could be useful to add to the `Select` type but I’m not sure what the API should look like exactly. ~Doubling the number of methods does not feel great.

For context: I’m building a priority queue on top of an array of crossbeam channels. My receiver should block until any of the inner receivers are ready, but then consume one item from the highest-priority channel rather than arbitrary one. (Starvation is mitigated by "ageing" some low-priority items into a one-level-higher priority channel.) As a work-around I call `Select::ready()` then an explicit loop with `Receiver::try_recv()`, but this looks like it does redundant work compared to an hypothetical `Select::biased_select()`

**Comment by taiki-e** [comment]
Added in crossbeam-channel 0.5.14 (#1150).
