### ISSUE TITLE
Crossbeam epoch and tokio async

### ISSUE THREAD

**Issue by ats1999** [crossbeam-rs/crossbeam#1164]
I was going through cross beam documentation and didn’t found any reference of tokio. I have to use `epoch` module to share data between threads(tokio task and async). 

Is cross beam epoch module support tokio async?

**Comment by taiki-e** [comment]
I'm not sure what your question means, but what epoch provides is a mechanism for memory reclamation, which has nothing to do with what async runtime you use.

**Comment by ats1999** [comment]
Thanks that clarifies the question, i just came across arc-swap crate, that doesn’t work well with rust async. So, was wondering if there is any such issue with cross beam as well. 

Limitation of arc-swap -> https://docs.rs/arc-swap/latest/arc_swap/docs/limitations/index.html
