### ISSUE TITLE
`join` to return a `Result<T>`?

### ISSUE THREAD

**Issue by dpc** [crossbeam-rs/crossbeam#126]
I was looking for a way to join on a thread to discover if it panicked. Did I miss anything?

**Comment by vojtechkral** [comment]
+1 I ran into the same problem.

Right now, unfortunatelly `ScopedJoinHandle` unwraps the std `JoinHandle` result, hindering panic handling (cf https://github.com/crossbeam-rs/crossbeam/blob/3521fd94e5f25a6f674aa06d6b864cbf17a29707/src/scoped.rs#L34).

I'd be willing to fix this, but I have to idea about crossbeam's API stability guarantees. Is it ok to change the API?

**Comment by bluss** [comment]
Maybe look into why rayon handles panics they way they do as well (I believe they propagate them without catching in a lot of cases). Since they have some domain knowledge

**Comment by stjepang** [comment]
I can see two ways to enable easier panic handling.

First, change the signature of `ScopedJoinHandle::join`:
```rust
fn join(self) -> T; // from this
fn join(self) -> thread::Result<T>; // to this
```

Second, add a new method on `Scope`, something like:
```rust
/// Returns `Ok(())` if all threads succeeded, or an error from one of the panicked functions.
fn join(self) -> thread::Result<()>;
```

@jeehoonkang, since you recently fiddled with scoped threads, do you have an opinion on all this?

**Comment by jeehoonkang** [comment]
I just copy-and-pasted codes from old commits..  I'll keep track of this issue, though.

**Comment by jeehoonkang** [comment]
I just implemented a joinable scoped thread API: https://github.com/crossbeam-rs/crossbeam-utils/pull/7 . Please have a look!
