### ISSUE TITLE
Question: Is there a way to limit capacity of crossbeam sync types?

### ISSUE THREAD

**Issue by algermissen** [crossbeam-rs/crossbeam#139]
I am using MsQueue and wonder whether I can prevent this queue from growing in an uncontrolled way?

Jan

**Comment by stjepang** [comment]
Unfortunately, no. If you want a bounded MPMC queue, I recommend [this](http://carllerche.github.io/syncbox/syncbox/struct.ArrayQueue.html) one.

We have a plan to build something similar as part of Crossbeam within the next several months.

**Comment by algermissen** [comment]
Thanks!
