### ISSUE TITLE
Add {Sync, Send} on ArcCell

### ISSUE THREAD

**Issue by icorderi** [crossbeam-rs/crossbeam#140]
Shouldn't `ArcCell` have `impl {Sync, Send}`?

I guess `T` has to be `Send`:

```rust
unsafe impl<T: Send> Sync for ArcCell<T> {}
unsafe impl<T: Send> Send for ArcCell<T> {}
```

**Comment by stjepang** [comment]
This is the definition of the struct:

```rust
pub struct ArcCell<T>(AtomicUsize, PhantomData<Arc<T>>);
```

`ArcCell` simply inherits the constraints of `Arc<T>` -- it is `Sync + Send` if `T: Send + Sync`.

**Comment by Vtec234** [comment]
While it is true that the inherited traits are correct, it might be worth it to consider explicitly `impl`ing or `!impl` ing `Send` and `Sync` for _all_ types in crossbeam, given the finnicky nature of concurrent programming. An example of when implicitness backfired is https://github.com/rust-lang/rust/issues/41622.

**Comment by stjepang** [comment]
@Vtec234 I agree. Also, it's good to have explicit impls for `Send` and `Sync` in the generated docs.
