### ISSUE TITLE
Value does not get moved back to scope after thread end

### ISSUE THREAD

**Issue by Nokel81** [crossbeam-rs/crossbeam#141]
Hello, I was shown this crate to help with multi-threaded sorting. From the examples in the doc I came to the conclusion that the following should work.

```rust
let mut left_half = array[0 .. half].to_vec();
let mut right_half = array[half .. whole].to_vec();
crossbeam::scope(|scope| {
    scope.spawn(move || i32_merge_sort(&mut left_half));
    scope.spawn(move || i32_merge_sort(&mut right_half));
});
```

However I get a lot of the following errors, which I think should be mentioned in the documentation on how to avoid.

```
error[E0382]: use of moved value: `left_half`
  --> src\main.rs:42:22
   |
29 |         crossbeam::scope(|scope| {
   |                          ------- value moved (into closure) here
...
42 |         while left < left_half.len() && right < right_half.len() {
   |                      ^^^^^^^^^ value used here after move
   |
   = note: move occurs because `left_half` has type `std::vec::Vec<i32>`, which does not implement the `Copy` trait
```

**Comment by stjepang** [comment]
By the looks of the error message, it seems you didn't show us the whole code. :)
Could you paste the whole code (in particular, I'd like to see everything between lines 29 and 42, and a bit more)?

But anyways, you probably want to split the array like this:

```rust
let (left_half, right_half) = array.split_at_mut(half);
crossbeam::scope(|scope| {
    scope.spawn(|| i32_merge_sort(left_half));
    scope.spawn(|| i32_merge_sort(right_half));
});
```

This recursively calls merge sort with two slices of the `array`. Your code seems to create *copies* of the two halves, and then sorts those copies recursively.

For tasks like this one, Rayon would probably be a better fit than Crossbeam's scoped threads. In fact, Rayon demonstrates parallel merge sort in [one of it's demos](https://github.com/nikomatsakis/rayon/blob/0a7a1be73c0e68d7ebc1adbf7c1ca741110d38d6/rayon-demo/src/mergesort/mod.rs#L59).

**Comment by Nokel81** [comment]
Thanks I will ask over there
