### ISSUE TITLE
`AtomicOption` should run `Box::drop` on drop.

### ISSUE THREAD

**Issue by quadrupleslap** [crossbeam-rs/crossbeam#142]
Right now it's leaking memory and not running destructors. This is necessary:

```rust
impl<T> Drop for AtomicOption<T> {
    fn drop(&mut self) {
        let inner = self.inner.load(Ordering::SeqCst);
        if !inner.is_null() {
            unsafe { Box::from_raw(inner); }
        }
    }
}
```

Playground: https://is.gd/FUK0pr

**Comment by spacejam** [comment]
just hit this while sanitizing for leaks...

**Comment by spacejam** [comment]
mostly copied your code but SeqCst -> Relaxed because `drop` shouldn't get reordered before another thread's access.

https://github.com/crossbeam-rs/crossbeam/pull/153
