### ISSUE TITLE
return vector after move

### ISSUE THREAD

**Issue by yoni386** [crossbeam-rs/crossbeam#143]
Hello,

Is there a way to use something after it moved? in general, I spawning a thread to do some long task then push them to a vector and use outside this function. 
is it possible? in this case crossbeam or threads or channels are better to use?
 
https://is.gd/BqUasR

use std::sync::Arc;
use std::{thread, time};

pub fn builder(objects: Vec<&str>) -> TraitVec {
    let mut trait_vec: TraitVec = Vec::new();
    let data = Arc::new(Mutex::new(trait_vec));
    crossbeam::scope(|scope| for object in &objects {
                         let data = data.clone();
                         scope.spawn(move || 
                            if let Some(object) = builder_obj(object) {
                                let mut data = data.lock().unwrap();
                                data.push(object);
                            });
                     });
    trait_vec

}

fn main() {
    let objects = Vec::new("1", "2");
    let v = builder(objects);
}

**Comment by stjepang** [comment]
Instead of returning `trait_vec` at the end, perhaps you want return the following?

```rust
std::mem::replace(&mut *v.lock().unwrap(), Vec::new())
```

If you're generating a lot of objects, there might be heavy contention on the mutex, thus slowing everything down. In that case using a channel to put objects into could be more efficient here.

**Comment by jeehoonkang** [comment]
I'd like to recommend [`crossbeam-channel`](https://github.com/crossbeam-rs/crossbeam-channel) for your use case.

Closing it :)
