### ISSUE TITLE
Update crate level documentation?

### ISSUE THREAD

**Issue by DaseinPhaos** [crossbeam-rs/crossbeam#156]
First of all thanks for this great crate!

I found some nits in the doc though, thus this issue.

The crate level documentation ([here](https://docs.rs/crossbeam/0.3.0/crossbeam/)) seems to be mentioning a non-existential module called `mem`. The description also doesn't match up with the repo README.

Maybe the crate level doc should be updated?

**Comment by jeehoonkang** [comment]
Thank you for bringing up the issue!  This should have been fixed in https://github.com/crossbeam-rs/crossbeam/commit/8203c9f3ec8a24ab66aa68a3304d12b4a96c835e, but we didn't publish the crate yet.  Maybe we should make a 0.3.1 point release.

**Comment by DaseinPhaos** [comment]
Thanks for the reply! Oh I missed #152 and #155 .. Closing..
