### ISSUE TITLE
Epoch types that are "unlinked" can not impl Drop

### ISSUE THREAD

**Issue by Firstyear** [crossbeam-rs/crossbeam#161]
Most implementations currently using crossbeam::epoch are internal details of datastructures - for examples queue nodes. 

However for more complex concurrently readable structures (single writers, multiple concurrent reads over generations), the types that crossbeam::epoch is protecting may not be an internal detail. They become external generic types.

During the creation of a concurrently readable box type, I discovered that types implementing Drop do *not* have fn drop called on the type.

This means that crossbeam::epoch is not capable of storing types like Vec<> or String. 

There are two possible solutions.

First, is to enforce that types epoch can unlink implement Copy (as this excludes Drop).

An alternate is to change the epoch api to be "type based" and take generics. It appears to me that the current implementation stores garbage from *all* structures together in the same garbage bags, and as a result they are treated as generic pointer types during drop - there is no way to reconstruct what type it may have been because now you only have a pointer. 

Example code can be found in: https://github.com/Firstyear/idl_rust/blob/master/src/ebrcell.rs 

The test triggering this is an attempt to detect that I had implement unlinking correctly for types, which involves adding a type to the box implementing a custom drop that would trigger an atomic which we could check "drops are occuring".

For curiosity, the same "pattern" built with Arc + rwlock does correctly work. The issue lies in epoch garbage collections clean up and drop code. 

Thanks,

**Comment by Firstyear** [comment]
Let me expand this a little. I think this issue unfolds into quite a number of issues.

I think "Copy" as a trait for epoch types to be unlinked, or rather "Copy and NOT Clone" types may be the correction solution. See, there is one type that kinda breaks the rules: Arc<T>. 

If you put an Arc<T> in a conc box, the issue is that on clone(), you get a mutable reference to a type that is possibly still under read from a previous generation. And this isn't just a limitation of my implementation, think about this in a Queue type - modifying queued elements without safety would break many rust guarantees.

Arc almost needs a special "magic clone" type. We have things like String and Vec<T> that are clone, for good reason, to clone their inner types if they also implement clone. They are complex and require special care. Same with Drop. But Arc with a "clone" is more like "well, here's the thing but with a different wrapper on it". You can still violate some of it's rules. Arc when dropped has to drop it's *inner* types too.

So epoch just isn't built to handle this. It needs to exclude Arc, allow .clone() for vec/string, and then allow custom drops.

In the perfect world, the best solution is a *per structure* epoch type that has enforced generics, rather than "thread global garbage" types. This would allow proper .drop to work on the type (no need for *mut). The only quirk then is exclusion of Arc/Rc, which I'm not sure how to achieve.

Hope this helps,

**Comment by martinhath** [comment]
The epoch part of Crossbeam has been moved to [crossbeam-rs/crossbeam-epoch](https://github.com/crossbeam-rs/crossbeam-epoch). Do you know if this is a problem there as well? 

It was my understanding that one of the ideas behind having the `Garbage` struct was exactly to be able to `drop` any type, and that this was handled [here](https://github.com/crossbeam-rs/crossbeam/blob/master/src/epoch/garbage.rs#L43) (although I do find it weird that the length of the Vec is set to zero instead of one, which, presumably, causes no `drop` to be called). Anyways, I suggest you take a look at `crossbeam-epoch` 😄

**Comment by Firstyear** [comment]
First, why does crossbeam not use crossbeam-epoch? Why is it still using the internal version? 

Anyway, it works with the new crossbeam-epoch crate if I use:

```
        let prev_data = self.active.load(Relaxed, &guard);
        unsafe {
            guard.defer(move || {
                drop(prev_data.into_owned());
            });
        }
```

So really, this repo needs to 

* Advertise that it's defunct
* Fix this repo to use crossbeab-epoch
* Something else?

**Comment by Vtec234** [comment]
@Firstyear The project is currently in a transition period. When `crossbeam-epoch` is certain to be equivalent in functionality to the current `crossbeam` and has been tested enough, this crate will be switched over to use `crossbeam-epoch`.

**Comment by Firstyear** [comment]
Okay, thanks for the explanation. Again, it would be great to have this notified ... somewhere, because as a first time consumer of the API this seems like a very large API change, and behavioral change, so it would be good to have new consumers exposed to the crossbeam-epoch version instead.

In a way, this ties back to a previous complaint about separation of the crates - it creates confusion and fragmentation where there really shouldn't be any  :(
