### ISSUE TITLE
General versioning consistency of the crossbeam family

### ISSUE THREAD

**Issue by silwol** [crossbeam-rs/crossbeam#190]
When packaging crossbeam for Debian, the team stumbled upon some inconsistencies in the crossbeam crate family.
This is a quick overview of the current state of the dependency tree:
```
╭───────────────╮
│crossbeam 0.4.1│
╰───────────────╯
 │   │   │   └───────────────────────────────────────────────┐
 │   ▼   └──────────────────┐                                ▼
 │  ╭─────────────────────╮ │ ╭─────────────────────╮  ╭───────────────────────╮
 │  │crossbeam-deque 0.5.2│ │ │crossbeam-deque 0.6.1│  │crossbeam-channel 0.2.6│
 │  ╰─────────────────────╯ │ ╰─────────────────────╯  ╰───────────────────────╯
 │    │              │      │   │      │                │       │
 │    │              ▼      ▼   ▼      │   ┌────────────┘       ▼
 │    │       ╭─────────────────────╮  │   │    ╭─────────────────────╮
 │    │       │crossbeam-epoch 0.5.2│  │   │    │crossbeam-epoch 0.6.0│
 │    │       ╰─────────────────────╯  │   │    ╰─────────────────────╯
 │    │                            │   │   │   ┌──────────┘
 │    └────────────────────────┐   │   │   │   │
 └─────────────────────────┐   │   │   │   │   │
                           ▼   ▼   ▼   ▼   ▼   ▼
                          ╭─────────────────────╮
                          │crossbeam-utils 0.5.0│
                          ╰─────────────────────╯
```
The major problematic points for us are:
- crossbeam has multiple versions of crossbeam-epoch in it's dependency tree (as mentioned in https://github.com/crossbeam-rs/crossbeam-deque/issues/17)
- The crossbeam-deque dependency of crossbeam is 0.5, not the latest version 0.6 (which might be pulled in by other crates depending on it)

I don't know the details and internals of the crossbeam project, but from a user and packager's perspective it would be easiest and least confusing if the family in itself would have only the latest version of each crate in it's dependency tree.

**Comment by jeehoonkang** [comment]
#210 partially solves this problem.

I think, maybe, it would be convenient to release crossbeam families in lock-step: releasing crossbeam-* 0.x at the same time.  This scheme can be used after reaching 1.0, too.

**Comment by stjepang** [comment]
An interesting issue to follow: https://github.com/tokio-rs/tokio/issues/572

**Comment by stjepang** [comment]
I've just published new versions of crossbeam crates. The duplicate dependencies problem is now resolved.
