### ISSUE TITLE
A method to query the scope if anything panicked

### ISSUE THREAD

**Issue by vorner** [crossbeam-rs/crossbeam#196]
Let's say I have a code like this:

```rust
thread::scope(|scope| {
    scope.thread(|| for item in long_vector {
        do_stuff(item);
    });
    scope.thread(|| for item in another_long_vector {
        do_stuff(item);
    });
});
```

Now, if one of the threads panics, the scope has little choice than wait for the other to terminate as well, which could be a long time (or, in certain cases, might never happen, because it relies on the existence of the dead thread).

It would still be useful to at least be able to query the scope if any of the threads panicked and let the thread terminate on its own will, eg:

```rust
scope.thread(|| for item in long_vector {
    if scope.anything_panicked() {
      break;
    }
    do_stuff(item);
});
```

**Comment by jeehoonkang** [comment]
I agree with @stjepang on this issue.  We can implement status trackers on top of scoped threads and other utilities, so I don't see much necessity for adding it as a feature.  Furthermore, tracking the status will add a slight overhead, which I would like to avoid in a general-purpose library.

**Comment by khuey** [comment]
I came across a similar problem today: I have a producer thread and a consumer thread in a crossbeam::scope and if one side panics the entire thing deadlocks permanently. This is a pretty annoying footgun.

**Comment by taiki-e** [comment]
crossbeam's scope threads have been soft-deprecated in favor of the more efficient std::thread::scope that stabilized on Rust 1.63, so there are no plans to accept new APIs to it.
