### ISSUE TITLE
Implement OS-specific methods on ScopedJoinHandle

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam#197]
See impls of `JoinHandleExt`, `AsRawHandle`, and `IntoRawHandle` here:
https://doc.rust-lang.org/nightly/std/thread/struct.JoinHandle.html

**Comment by blitzerr** [comment]
Hi @stjepang, I would like to contribute to this one. If I need to ask for help, where should I reach out? Any email, zulip etc. I can reach people ?

**Comment by stjepang** [comment]
Hi @blitzerr, that'd be awesome! :)
You can reach out either here on GitHub or in `#crossbeam` at `irc.mozilla.org`.

**Comment by blitzerr** [comment]
Thanks a lot.
