### ISSUE TITLE
Document environment requirements

### ISSUE THREAD

**Issue by sanmai-NL** [crossbeam-rs/crossbeam#198]
Can this component work in a `no_std` environment? If not, can it with `alloc`? If any, what allocations are done and when can panics occur? What about OS compatibility? What are the strategic priorities in this regard, and have those materialized in a planning? If you were to provide the main environment requirements in tabular format in the `README`, that would help greatly to evaluate this crate and `crossbeam` in general for take-up in industry. :slightly_smiling_face:

**Comment by stjepang** [comment]
Some of these questions are answered by #251.

If there's anything else you'd like me to write there, let me know!
