### ISSUE TITLE
crossbeam-epoch dependency outdated

### ISSUE THREAD

**Issue by kpcyrd** [crossbeam-rs/crossbeam#202]
Hello!

We noticed there was a new crossbeam-epoch release, would you mind bumping the dependency in crossbeam-deque?

Thanks!

**Comment by kpcyrd** [comment]
Awesome, would you mind pushing a new release? :) https://crates.io/crates/crossbeam-deque was last updated 3 months ago and still uses crossbeam-epoch 0.5

**Comment by stjepang** [comment]
@kpcyrd Yep, I'll do it as soon as possible. Let's just land #217 before the new release.

**Comment by stjepang** [comment]
New versions have been released.
