### ISSUE TITLE
Release plan? [of crossbeam-skiplist]

### ISSUE THREAD

**Issue by crlf0710** [crossbeam-rs/crossbeam#203]
Hello, wonder if this crate is ready for publishing on `crates.io` soon? If not, is there a plan or a list of what's left so maybe others can help?

**Comment by jeehoonkang** [comment]
Unfortunately, the issue numbers in the body are broken :(  @stjepang would you please update them so that we can easily track the issues status?

**Comment by crlf0710** [comment]
For reference, `#3` mentioned above is #205, and `#7` above is #204

**Comment by CameronNemo** [comment]
What is the state of skiplist? I see that `https://docs.rs/chashmap/2.2.2/chashmap/` is available. Seems to fulfill part of what skiplist does / is intended to do.

**Comment by aloucks** [comment]
This crate looks promising! Any update on the release plan?

**Comment by taiki-e** [comment]
Closing in favor of #635
