### ISSUE TITLE
Add `.is_empty()` on queues?

### ISSUE THREAD

**Issue by dpc** [crossbeam-rs/crossbeam#22]
I'm not aware if lack of `is_empty()` on the queues is technical limitation, but it would be nice to have. I am aware that between `.is_empty()` and `.pop()` state of the queue can change, but in some cases it's irrelevant or can't happen (eg. just one receiver).

**Comment by Ticki** [comment]
I added `.is_empty()` to `MsQueue` in #34.

**Comment by Ticki** [comment]
#34 is merged now.

I added #35 which adds `.is_empty()` to `TreiberStack`s.

**Comment by stjepang** [comment]
All queues have `is_empty()` now.
