### ISSUE TITLE
Please add a copy of CC-BY to the repo

### ISSUE THREAD

**Issue by erickt** [crossbeam-rs/crossbeam#228]
Hello! I'm sorry I missed this in https://github.com/crossbeam-rs/crossbeam-channel/issues/104, but would it be possible to include a copy of [CC-BY 3.0](https://creativecommons.org/licenses/by/3.0/) for the example in https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-channel/examples/matching.rs? Thanks so much!

**Comment by stjepang** [comment]
Sure, no problem!

So I'm not an expert at licensing, but the license text is ridiculously long, which makes the source file with a simple example look kind of silly. :) Is there a better way to license code and give credit to previous work?

There are a few other places with copies of licenses:

* https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-channel/tests/mpsc.rs
* https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-channel/src/flavors/array.rs
* https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-channel/tests/golang.rs

Would it be better to just mention the license used and move all those license texts into a single `COPYRIGHT` file?

**Comment by erickt** [comment]
Hello @stjepang! Thanks for the quick reply again.

My vote would you to add the full text of the license to a `LICENSE` or a `LICENSE-CC-BY` file, which could be at the top-level, or in the subdirectory if it's only used in that directory. Then just explain in the `README.md` to say which files are covered by these licenses.

I really appreciate all this work you are doing for us!
