### ISSUE TITLE
Concurrent vector?

### ISSUE THREAD

**Issue by crlf0710** [crossbeam-rs/crossbeam#239]
Hello, i'm not sure if this is even a correct question to ask. I've got vector-like data to share between threads. Its elements are atomic, say, `AtomicUsize` or `ArcCell`, so concurrent reading and writing has no problem.  Rarely, but occasionally i want to remove one element or append one element to the vector. I feel that a lock here is too much weight, since the number of elements doesn't usually change most of the time! I wonder if there's something you would recommend in Rust. I've looked at crossbeam-deque but the API doesn't seem like what i would need. and with crossbeam-skiplist i'll have to deal with an extra Key type.

**Comment by stjepang** [comment]
Hello! So if I understood correctly, you'd like a data structure with the following interface?

```rust
impl Vector<T> {
    fn append(&self, t: T);
    fn remove(&self) -> Option<T>;
    fn iter(&self) -> Iter<'_, T>;
}
```

**Comment by crlf0710** [comment]
Hi, @stjepang. Yes, i think that's what i want. Do you have any suggestions?

**Comment by stjepang** [comment]
We don't have anything like it at the moment. Perhaps [this](https://github.com/paulocsanz/voluntary-servitude) might be what you're looking after (I haven't used it, but the description seems to fit your requirements).

**Comment by crlf0710** [comment]
Thank you! i'll take a lot.
