### ISSUE TITLE
Select::remove() for removing operations

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam#252]
`Select::remove()` might be a useful method to add. For example, then we could call `sel.remove(index)` to remove a previously added operation.

After an operation has been removed from a `Select`, adding new senders/receivers would not reuse old indices.

This is just an idea. If you think adding this method would be useful, let me know!

**Comment by hahseba** [comment]
Definitely useful IMO, I was surprised it wasn't there yet.

**Comment by stjepang** [comment]
@hahseba That's good to hear!

Do you have a certain use case in mind? I'm asking to see what kind of interface would work well here.

**Comment by hahseba** [comment]
Something like this:
```
    let (x, y) = crossbeam_channel::unbounded::<u8>();
    // move y into some object that we pass to the thread 
    thread::spawn(move || {
        let mut sel = Select::new();
        {
            let handle_y = sel.recv(&y);
            loop {
                let oper = sel.select();
                match oper.index() {
                    i if i == handle_y => {
                        match oper.recv(&y) {
                            Ok(val) => println!("{}", val),
                            _ => break
                        }
                    }
                    _ => unreachable!()
                }
            }
        }
        // Drop the object containing y because we don't need it anymore after the sender sent us a message
        drop(y);
    });
```

Right now the drop(y) doesn't work because `sel` still borrows it.

**Comment by stjepang** [comment]
If you're using Rust 2018 (with non-lexical lifetimes), doing `drop(sel)` before `drop(y)` should work.

**Comment by hahseba** [comment]
Sorry, for brevity I left out part of the usecase. I would Keep using sel with other channels (and maybe add more, too).

**Comment by abreis** [comment]
I have a use-case as well: I have a real-time data pipeline where data is fed using channels, one per input.

Some inputs may wrap up sooner than others (by minutes, in some cases), and they signal their completion by closing the sender.

Right now I'm recreating `Select` whenever one of its channels gets dropped, which isn't exactly elegant. Would be great to have a `remove()` method!

**Comment by stjepang** [comment]
Just opened a PR adding a method that can disable an operation in `Select`.

@abreis How does that look?

**Comment by abreis** [comment]
Just tried your `select-disable` branch and yes, it works great. Code is more intuitive now: we match on the `select.recv()` and we can `select.disable()` right inside the `Err` variant.

Thanks!

**Comment by stjepang** [comment]
@abreis Great! Is your code public by any chance? If so, I'd be curious to take a look (always good to study real-world uses of this crate).

**Comment by abreis** [comment]
It's not, but I'm happy to share this snippet with you. I'll send you an email in a bit.

**Comment by shahn** [comment]
Awesome! This means I can get rid of quite a bit of code that only exists to keep some Senders around
