### ISSUE TITLE
Ergonomic losses when using `select!` with optional receiver (crossbeam-channel 0.2 to 0.3)

### ISSUE THREAD

**Issue by mchesser** [crossbeam-rs/crossbeam#257]
I use crossbeam-channel as a mechanism for managing connections to external resources that may meed to be re-established every so often. The connect function can be relatively expensive and the external resources may not be around for an extended period of time, so I only want to attempt to reconnect every so often, which I control using `channel::tick`.

Roughly I have variables that look like this:
```rust
let connect_to_external = || -> Option<Receiver<_>> {
    // ...
};

let controller_rx: Receiver<_> = ...
let mut external_rx: Option<Receiver<_>> = None;
let reconnect_tick = channel::tick(Duration::from_millis(1000));
```
(Note: in the actual code there are a variable number of `external_rx` variables and corresponding `connect_to_external` functions)

In crossbeam-channel 0.2 it was possible to use the `IntoIterator<Item=&Receiver<_>>` of `Option<Receiver<_>>` to use the `select!` macro, allowing the code to look something like this:

```rust
select! {
    recv(controller_rx, msg) => match msg {
        // ...
    },
    recv(external_rx, msg) => match msg {
        Some(value) => {
            // ..
        }
        None => {
            // ...
            external_rx = None;
        }
    },
    recv(reconnect_tick) => {
        if external_rx.is_none() {
            external_rx = connect_to_external();
        }
    }
}
```

Now in 0.3 the `Select` structure appears to be the only way to perform a select operation over multiple resources, requiring the following code:

```rust
let mut sel = channel::Select::new();

let controller_recv = sel.recv(&controller_rx);
let external_recv = external_rx.as_ref().map(|rx| sel.recv(rx));
let reconnect_recv = sel.recv(&reconnect_tick);

let op = sel.select();
match op.index() {
    i if i == controller_recv => match op.recv(&controller_rx) {
        // ...
    },
    i if Some(i) == external_recv => match op.recv(external_rx.as_ref().unwrap()) {
        Ok(value) => {
            // ...
        },
        Err(_) => {
            // ...
            drop(sel); // Assumes nll, (otherwise use option.take and replace it after)
            external_recv = None;
        }
    },
    i if i == reconnect_op => {
        let _ = op.recv(&reconnect_tick).unwrap();
        drop(sel);

        if external_rx.is_none() {
            external_rx = connect_to_external();
        }
    },
}
```

This translation _seems_ fairly automatic, so I was wondering if it was possible to recover some of the old `select!` macro with a slightly more complicated macro. (Or maybe, here a nicer way to achieve what I am trying to do?)

**Comment by stjepang** [comment]
> In crossbeam-channel 0.2 it was possible to use the `IntoIterator<Item=&Receiver<_>>` of `Option<Receiver<_>>` to use the `select!` macro

Yeah, sorry about that! The thing is, the mechanism behind allowing `IntoIterator` in `select!` was incredibly complicated and messy (with poor error messages on type mismatch and weaker type inference) so I decided to remove it.

> This translation _seems_ fairly automatic, so I was wondering if it was possible to recover some of the old `select!` macro with a slightly more complicated macro. (Or maybe, here a nicer way to achieve what I am trying to do?)

Yes, there is a nicer way using the [`never()`](https://docs.rs/crossbeam-channel/0.3.2/crossbeam_channel/fn.never.html) channel:

```rust
select! {
    recv(controller_rx) -> _ => match msg {
        // ...
    },
    recv(external_rx.unwrap_or(&never())) -> msg => match msg {
        Ok(value) => {
            // ..
        }
        Err(_) => {
            // ...
            external_rx = None;
        }
    },
    recv(reconnect_tick) -> _ => {
        if external_rx.is_none() {
            external_rx = connect_to_external();
        }
    }
}
```

Function `never()` returns a special kind of `Receiver<T>` that is never closed and messages are never delivered to it. By writing `external_rx.unwrap_or(&never())` you get this "blank" channel when `external_rx` is `None`.

There's only one example of this pattern in the docs so it doesn't seem very discoverable. I wonder how to change the docs to make it more visible. There are two ideas that come to my mind:

1. Add another example with the `never()` pattern to the examples section for [`select!`](https://docs.rs/crossbeam-channel/0.3.2/crossbeam_channel/macro.select.html).
2. Additionaly, perhaps add a new FAQ section to the [root docs section](https://docs.rs/crossbeam-channel/0.3.2/crossbeam_channel/index.html), where one of the questions would be "How to optionally add a channel to `select!`".

What do you think? Do you have any other suggestions?

**Comment by mchesser** [comment]
Ah I missed the addition of never -- it works great, thanks. I was mostly looking in the `select!` macro docs for the usage so having it there would help.

I did have some previous uses for the `IntoIterator` support, the new `Select` struct works fine in most cases.  However, without NLL it is slightly painful to use in some cases (I mostly experienced it when trying to call another method on `self` from within a select case), although the unbind trick that the select macro uses looks useful.

Also on docs, it would be nice to have some additional examples showing more complicated dynamic `Select` usages (e.g. selecting from items in a vec). It's fairly obvious after understanding how it works, however initially it wasn't clear since the example only shows a static case.
