### ISSUE TITLE
Allow selection of memory orderings for collection types

### ISSUE THREAD

**Issue by aturon** [crossbeam-rs/crossbeam#26]
Collections like queues work correctly under multiple memory orderings -- both `Acquire`/`Release` and `SeqCst`. Right now, the queues provide acquire/release semantics, but some applications may need stronger guarantees for e.g. relating multiple queues.

We should provide some way of selecting the level of guarantee.

**Comment by stjepang** [comment]
Many standard synchronization tools use `Acquire`/`Release` semantics: e.g. `std::sync::mpsc` and `std::sync::Mutex` (I think so). Is it worth providing stronger guarantees for them as well?

Do you perhaps have a concrete situation where this is needed for Crossbeam's collections, or is this just a hypothetical concern?

**Comment by stjepang** [comment]
> applications may need stronger guarantees for e.g. relating multiple queues.

I've chatted with @Amanieu about this. It turns out that:

* Even mutexes can't relate multiple queues (locking is not `SeqCst`).
* Read operations in reader-writer locks are possibly not `SeqCst` due to lock elision.

Given that, should we strive to provide `SeqCst` semantics in our data structures at all?

**Comment by Amanieu** [comment]
The consensus was that if you want `SeqCst` semantics then you should just wrap a pair of `SeqCst` fences around every queue operation.

**Comment by stjepang** [comment]
I wonder whether @jeehoonkang agrees. If so, we can close the issue.

**Comment by jeehoonkang** [comment]
I generally don't believe "sequential consistency" can give you much benefit: after all, its meaning is very vague.  In this spirit, I'm in favor of closing this issue.
