### ISSUE TITLE
Broken link on scoped thread spawning.

### ISSUE THREAD

**Issue by Darksonn** [crossbeam-rs/crossbeam#269]
On the documentation for [crossbeam::scope][1], the link with the label "scoped thread spawning" is broken.

Note that when the same function is accessed as [crossbeam_utils::thread::scope][2], the link is correct.

I recommend using an absolute link instead.

[1]: https://docs.rs/crossbeam/0.6.0/crossbeam/fn.scope.html
[2]: https://docs.rs/crossbeam-utils/0.6.3/crossbeam_utils/thread/fn.scope.html

**Comment by stjepang** [comment]
Thanks for the report! This has been fixed in #295.
