### ISSUE TITLE
Assertion failure in crossbeam-skiplist

### ISSUE THREAD

**Issue by crlf0710** [crossbeam-rs/crossbeam#270]
A friend of mine is trying to use nested `SkipMap`, but saw an assertion failure at
https://github.com/crossbeam-rs/crossbeam/blob/4b8a83569fcedf4d402ee6765fcbd44cfe4ec660/crossbeam-skiplist/src/base.rs#L128

Changing the value type to boxed solves the issue. But i wonder if this limitation is by design?

Haven't got time to write repro code yet, will write one if i've got time.

**Comment by stjepang** [comment]
We've just merged https://github.com/crossbeam-rs/crossbeam/pull/268, which simplifies node allocation and doesn't need this assert anymore. Can your friend try updating to the latest version on the master branch?

Also, if they have any feedback regarding `crossbeam-skiplist` to share, I'd love to hear! :)

**Comment by crlf0710** [comment]
He confirmed that current master branch is working ok now~ Thanks a lot!
