### ISSUE TITLE
Memory leak or gc not triggered?

### ISSUE THREAD

**Issue by crlf0710** [crossbeam-rs/crossbeam#273]
Hello, i'm not sure if there's a bug in code, or whether the epoch-based gc is not triggerly frequently enough, but my friend says this code can easily run out of system memory.

```rust
extern crate crossbeam_skiplist;
use crossbeam_skiplist::SkipMap;

struct TestDrop{
    i:i64
}
impl Drop for TestDrop {
    fn drop(&mut self) {
        println!("TestDrop Closing port, {}", self.i);
    }
}

fn main() {
    let m:SkipMap<String, TestDrop> = SkipMap::new();
    loop{
        m.clear();
        //for entry in m.iter(){
        //    entry.remove();
        //}
        for i in 0 .. 5000000{
            m.insert(format!("{}", i), TestDrop{i:i});
        }
        println!("map.len():{:?}", m.len());
    }
}
```

**Comment by jeehoonkang** [comment]
@crlf0710 Thanks for reporting it.  I'll soon look into this issue.

@stjepang do you have reasons to believe it's a bug in crossbeam-epoch, not in crossbeam-skiplist?  That information will help in localizing the bug :)

**Comment by crlf0710** [comment]
> Perhaps the allocator is just not returning memory to the OS?

I believe this is not the case, since he mentioned that `Drop::drop` is also not properly called.
