### ISSUE TITLE
"Receiving on an empty and disconnected channel" but why was it selected then?

### ISSUE THREAD

**Issue by hahseba** [crossbeam-rs/crossbeam#286]
I have some code where I have a bunch of threads which communicate via channels. Each sender and receiver has exactly one owner, no cloning of any kind. To create a shutdown mechanism, I've provided each thread with the receiver side of a special-purpose bounded(0) "kill" channel - the thread loops in a Select::select() call until it receives from the kill channel. The main thread then joins on all the threads and afterwards drops all the Senders.Of course all threads will not terminate at exactly the same time, but I thought that crossbeam would guarantee with that kind of setup that if select() returned, I could successfully recv() a message even if the Sender for the channel had already been dropped. Instead, I get the error message that I am receiving on an empty and disconnected channel. I understand that it is disconnected, because the thread which owns the sender likely went away, but why is it empty? Additionally, the "kill receiver" must not be disconnected yet, because its sender only gets dropped after all threads but the main thread have terminated. Nevertheless, I get some repeated log lines indicating that select() returns the same index again right away, with the call to recv() then failing immediately again.

I am on Windows 7 for this, if it matters. Is my understanding of what is going on flawed or is this possibly a bug?

**Comment by hahseba** [comment]
Reduced sample program which triggers (I hope) the same issue:

    loop {
        let (snd, rcv) = unbounded();
        let (snd_kill, rcv_kill) = bounded(0);

        let h1 = thread::spawn(move || {
            snd.send("wooooo");
        });
        let h2 = thread::spawn(move || {
            let mut sel = Select::new();
            let op = sel.recv(&rcv);
            let op_kill = sel.recv(&rcv_kill);
            loop {
                let oper = sel.select();
                match oper.index() {
                    i if i == op_kill => {
                            oper.recv(&rcv_kill).unwrap();
                            break;
                    }
                    _ => {
                        match oper.recv(&rcv) {
                            Ok(_) => {},
                            Err(x) => {
                                println!("{}", x);
                                std::process::abort()
                            }
                        }
                    }
                }
            }
        });
        snd_kill.send(()).unwrap();
        h1.join();
        h2.join();

    }

**Comment by stjepang** [comment]
The reason why the operation was selected is because it can proceed without blocking. Select will choose an operation that doesn't need to block, not an operation that will return an `Ok(..)`.

Perhaps you might like to remove `rcv` from `Select` once it becomes disconnected:

```rust
let h = thread::spawn(move || {
    let mut rcv = Some(rcv);
    loop {
        let mut sel = Select::new();
        if let Some(rcv) = &rcv {
            sel.recv(rcv);
        }
        let op_kill = sel.recv(&rcv_kill);
        let oper = sel.select();
        match oper.index() {
            i if i == op_kill => {
                    oper.recv(&rcv_kill).unwrap();
                    break;
            }
            _ => {
                match oper.recv(rcv.as_ref().unwrap()) {
                    Ok(_) => {},
                    Err(x) => {
                        println!("{}", x);
                        std::process::abort()
                    }
                }
            }
        }
    }
});
``` 

Or, alternatively, move a sender into the thread so that the channel doesn't get disconnected before it exits:

```rust
let h = thread::spawn({
    let mut snd = snd.clone();
    move || {
        let mut sel = Select::new();
        let op = sel.recv(&rcv);
        let op_kill = sel.recv(&rcv_kill);
        loop {
            let oper = sel.select();
            match oper.index() {
                i if i == op_kill => {
                        oper.recv(&rcv_kill).unwrap();
                        break;
                }
                _ => {
                    match oper.recv(&rcv) {
                        Ok(_) => {},
                        Err(x) => {
                            println!("{}", x);
                            std::process::abort()
                        }
                    }
                }
            }
        }
        drop(snd);
    }
});
```

**Comment by hahseba** [comment]
Thank you for the fast reply. In your first suggestion, what actually sets `rcv` to `None` though? I do not see how it would work. The second suggestion totally does the trick, though it looks a bit ugly in my real program.

**Comment by stjepang** [comment]
> In your first suggestion, what actually sets `rcv` to `None` though? I do not see how it would work.

Sorry, I forgot to add `drop(sel); rcv = None;`. I've updated the comment so please take another look.

**Comment by hahseba** [comment]
Ok, thanks! I see that I misunderstood the API. I thought it meant that `select` would return immediately if it had only disconnected channels to work with, not that it would do it if any of the channels were disconnected. Sorry for the noise!
