### ISSUE TITLE
Priority queue version of deque

### ISSUE THREAD

**Issue by thedrow** [crossbeam-rs/crossbeam#289]
Right now our deque implementation does not support priorities.
It'd be a useful feature for me and possibly others.
Can we add a deque version that supports priorities?

**Comment by stjepang** [comment]
I'm not sure how to handle priorities efficiently in a generic manner, so the answer is no.
Perhaps it's best to simply define a handful of priority classes and have one deque for each priority class?

**Comment by thedrow** [comment]
Why not? What's preventing us from doing so?

**Comment by stjepang** [comment]
Intel TBB has [`concurrent_priority_queue`](https://www.threadingbuildingblocks.org/docs/help/reference/containers_overview/concurrent_priority_queue_cls.html). While we technically could implement something similar, I don't think it's worth the effort. It's pretty much a useless data structure.

See this post by Dmitry Vyukov for a good explanation: http://www.1024cores.net/home/lock-free-algorithms/queues/priority-queues

**Comment by thedrow** [comment]
We could provide an adapter which takes the approach you suggested.

**Comment by stjepang** [comment]
Could you perhaps describe an interface you'd ideally like or tell more about your particular use case? For example, how many priority classes there are? Or, does every worker thread always need to process tasks with the highest priority, or simply pick tasks of higher priority with higher probability?

**Comment by jeehoonkang** [comment]
I'm kinda trying to do some triage, and would like to close this for inactivity.  @thedrow Please reopen it if you have more opinions on priority queues!

**Comment by thedrow** [comment]
Yes sorry for neglecting this issue. 
I'd say that any consumer must take the item with the highest priority first. We can provide an implementation that does that on a best effort basis if it trades performance with absolute correctness.
The number of priorities should be pre-assigned when constructing the queue.
