### ISSUE TITLE
Is it possible to have a channel with a buffer size of 1 that would discard messages when full?

### ISSUE THREAD

**Issue by bbigras** [crossbeam-rs/crossbeam#293]
Let say I want to send an HTTP request each time an event happens so I can refresh some cache.

The events can sometime happen faster (or more often) than I can send the HTTP request.

I only want to get at least a notification after the last event so it could make sense to have a channel with a buffer of size 1 that would discard new messages.

**Comment by stjepang** [comment]
Sounds like you want a `bounded(1)` channel and use `.try_send(msg)` to send messages into it. If the channel is full, the message will be discarded.

Is that it, or did I misunderstand something?

**Comment by bbigras** [comment]
Yes. That sounds exactly like it. Thank you very much.
