### ISSUE TITLE
Docs for `crossbeam::scope` give wrong link because it's a re-export.

### ISSUE THREAD

**Issue by Lokathor** [crossbeam-rs/crossbeam#296]
The docs for [crossbeam::scope](https://docs.rs/crossbeam/0.6.0/crossbeam/fn.scope.html) have a link about `scoped thread spawning` but that goes to a dead location since it's a relative link that only works within the `crossbeam_utils` crate.

**Comment by stjepang** [comment]
Thanks for the report! This has been fixed in #295. I'll publish a new version soon so that new docs get generated.
