### ISSUE TITLE
SkipMap get_mut

### ISSUE THREAD

**Issue by normano** [crossbeam-rs/crossbeam#318]
There is another skipmap implementation in another crate that returns a mutable reference to a value, so I'm wondering if that is possible here? Entry only supports value which gives immutable reference.

**Comment by stjepang** [comment]
Do you have a link to that skipmap implementation? If it works there, I don't see a reason why we couldn't add it here, too (unless it's unsound). :)

**Comment by Amanieu** [comment]
I believe the other skipmap is a non-concurrent variant, which makes it safe to return mutable references to elements. crossbeam's `SkipMap` is concurrent, which means that other threads may also be holding references to returned elements. So it cannot return a mutable reference.

**Comment by normano** [comment]
Yeah, it is non-concurrent variant. https://github.com/rocallahan/rust-stable-skiplist/blob/master/src/skipmap.rs

I wanted to know if it was possible since the value itself may be a "thread-safe" container where it would be safe to add/remote objects, but the Entry<k,v> does not have to change.

**Comment by stjepang** [comment]
Well, perhaps you could wrap the value in a mutex? So something like `SkipMap<K, Mutex<V>>`?

**Comment by normano** [comment]
That'll likely work. Thanks!
