### ISSUE TITLE
Queue blocking on `.pop()` when empty

### ISSUE THREAD

**Issue by fulmicoton** [crossbeam-rs/crossbeam#324]
Tantivy implements its pool of `Searcher` using a `MsQueue`.
By default, it populates the pool with `num cpus` searchers, the user borrows one to perform a search query,
and the query is pushed back into the queue on `Drop`.

In the context of a search server with a one thread per request model, this has the benefit of increasing throughput by avoiding everyone to try to perform computation on the index at the same time.

This relies heavily on the idea that `.pop()` blocks efficiently when the queue is empty, and returns when a searcher is released back into the pool.
According to the documentation, `SegQueue`'s `pop()` does not offer the same semantics. It returns an error when the queue is empty. Is my understanding correct, or does it return an error only when the producer is dropped?

If so, is there something in crossbeam that can address my problem? 
Granted, using a queue as a pool of object might be an abuse of queues. Feel free to point me to another solution/crate.

**Comment by BurntSushi** [comment]
Why doesn't crossbeam-channel work for you?

**Comment by fulmicoton** [comment]
Ah, yes that seems to be what I need. Thanks.
