### ISSUE TITLE
crossbeam-based alternative to mpsc_requests

### ISSUE THREAD

**Issue by ErikBjare** [crossbeam-rs/crossbeam#353]
Hi there, I'm building [ActivityWatch](https://github.com/ActivityWatch) and one of our main modules is [aw-server-rust](https://github.com/ActivityWatch/aw-server-rust) (which is also used by [aw-android](https://github.com/ActivityWatch/aw-android)).

We're using a multi-producer single-consumer queue to perform operations on a SQLite database on HTTP requests.

However, we stumbled upon a weird issue in mpsc (https://github.com/ActivityWatch/aw-android/issues/13) that only seems to happen on armv8 (Android), and while we're curious what could cause it, we're not that interested in the difficult process of hunting the issue down and would like to switch over to crossbeam anyway.

We've been using [mpsc_requests](https://docs.rs/mpsc_requests/0.2.0/mpsc_requests/) to be able to make the SQLite thread return results when the queued action is completed. I searched around but couldn't find anything similar for crossbeam (although it's totally possible that my Rust Google-fu is weak).

Sorry for pestering your issues with non-bug issues like this, but I assumed it'd be useful for others who might face a similar question in the future.

Edit: As @johan-bjareholt suggested in a PM to me, it might just make the most sense to reimplement mspc_requests for crossbeam, as the codebase is [really really small](https://docs.rs/crate/mpsc_requests/0.2.0/source/src/lib.rs).

**Comment by stjepang** [comment]
Hi! As far as I know, there is currently no `mpsc_requests` based on `crossbeam`, but as you already said, it's pretty easy to switch.

In fact, here's a quick port of `mpsc_requests` to `crossbeam` I just did: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f6dfce3c1be37c5de53ef04f6554dcfd

In order to use this, you'll need to add `crossbeam-channel` dependency to your `Cargo.toml`:

```toml
[dependencies]
crossbeam-channel = "0.3.8"
```

**Comment by ErikBjare** [comment]
Amazing, works great! Set you as the author on the commit (https://github.com/ActivityWatch/aw-server-rust/commit/04fb158fd5ba3ab5683c24432a9ddd06443c2a08)  that adds crossbeam_channel to our repo, to acknowledge your contribution. 

Thanks a lot, you're the real MVP :100: :+1:
