### ISSUE TITLE
expired discord invite

### ISSUE THREAD

**Issue by memoryruins** [crossbeam-rs/crossbeam#362]
The readme's invite to the discord server is currently invalid/expired:
![invite-expired](https://user-images.githubusercontent.com/6868531/56589781-e6f6dc00-65b3-11e9-8939-6be43a9f2a1c.png)

**Comment by Restioson** [comment]
Perhaps it was deleted by accident

**Comment by stjepang** [comment]
Should be fixed now. The new link is: https://discord.gg/JXYwgWZ
