### ISSUE TITLE
Repeat/Replay of value(s) for new Receivers

### ISSUE THREAD

**Issue by artem-zinnatullin** [crossbeam-rs/crossbeam#367]
Hi, sorry if this is already asked/answered somewhere (I've tried searching).

I'm looking for a way to repeat/replay last value(s) sent to a Channel for Receivers coming late to the party.

If you're familiar with Reactive Streams, there are operators like [`replay()`](http://reactivex.io/documentation/operators/replay.html), [`cache()`](http://reactivex.io/documentation/operators/replay.html), [`replayingShare()`](https://github.com/JakeWharton/RxReplayingShare).

I'm wondering if there is a similar thing for Channels, right now I have to do weird tricks, basically only receive value once in the program flow but in multiple places in the code to achieve that effect.

Semantically, this feature could probably look like this:

```rust
let (tx, rx): (Sender<Something>, Receiver<Something>) = unbounded().replay(n);

let result1 = rx.recv().unwrap();

// somewhere later
let result2 = rx.recv().unwrap();

assert_eq!(result1, result2);
```

**Comment by stjepang** [comment]
Would perhaps the [`bus`](https://docs.rs/bus/2.2.1/bus/) crate work for your use case?

**Comment by artem-zinnatullin** [comment]
It seems so! Thanks for pointing me to that crate, I'll close this issue then 👍
