### ISSUE TITLE
crossbeam_epoch::Atomic::into_owned

### ISSUE THREAD

**Issue by vorner** [crossbeam-rs/crossbeam#369]
Hello

I'm wondering why the `Atomic` doesn't have an `unsafe fn into_owned(self) -> Owned<T>` method. I'd find it handy in a data structure destructor, when I'm sure that no concurrent accesses are being made to the structure any more, as it's in the destructor which is `&mut self`.

Now, I can do a load on the atomic with `epoch::unprotected` and convert that shared. But is there a particular reason why the above method doesn't exist? If not, is it OK if I send a PR?

**Comment by stjepang** [comment]
There is no particular reason why it doesn't exist - a PR would be welcome!
