### ISSUE TITLE
[Question] Can I use crossbeam to handle broadcast messages?

### ISSUE THREAD

**Issue by gbonnema** [crossbeam-rs/crossbeam#374]
I want to create a subscription to a notify of certain events. I am already using `mpsc` for the single consumer case. Now I want to broadcast stuff.

My understanding of crossbeam is that I *can* use multiple consumers, but once a message is consumed, then it disappears. In other words: it is not broadcast to all consumers.

Could I use the crossbeam for broadcasting messages?

P.S. I am a rust newcomer, and not a pro programmer.

**Comment by stjepang** [comment]
Unfortunately, you can't. That would be possible using the `bus` crate.

Alternatively, you could create a channel per subscriber, hold a `Vec<Sender<T>>` on the producer side, and then send a copy of the message for each subscriber.

**Comment by gbonnema** [comment]
Fair enough, thanks for the response :).

**Comment by WyseNynja** [comment]
The bus crate is bounded and I needed an unbounded queue, so this is the quick and dirty code I came up with. It could definitely be improved and the bounds are probably not right, but it works for me for now.

```
pub struct UnboundedBroadcast<T> {
    channels: Vec<crossbeam_channel::Sender<T>>,
}

impl<T: 'static + Clone + Send + Sync> UnboundedBroadcast<T> {
    pub fn new() -> Self {
        Self { channels: vec![] }
    }

    pub fn subscribe(&mut self) -> crossbeam_channel::Receiver<T> {
        let (tx, rx) = crossbeam_channel::unbounded();

        self.channels.push(tx);

        rx
    }

    pub fn send(&self, message: T) -> Result<(), crossbeam_channel::SendError<T>> {
        for c in self.channels.iter() {
            c.send(message.clone())?;
        }

        Ok(())
    }
}
```
