### ISSUE TITLE
[crossbeam-channel] Select which can consume rx/tx

### ISSUE THREAD

**Issue by tekjar** [crossbeam-rs/crossbeam#387]
I'm creating an abstraction over receiver which can orchestrate between disk and memory. Minimal version of it looks like this

```rust
pub struct Receiver {
    priority_queue_2: crossbeam_channel::Receiver,
    priority_queue_1: crossbeam_channel::Receiver,
    select: Select,
}

impl Receiver {
    pub fn new(priority_queue_2: Receiver, priority_queue_1: Receiver) -> Self {
        let mut select = Select::new();
        select.recv(&priority_queue_2);
        select.recv(&priority_queue_1);

       Receiver {
            select,
            priority_queue_2,
            priority_queue_1,
        }
    }
}
```
Plan is to use `self.select()` in my `recv` but the above pattern is creating a self referential struct.  Is it possible to move `rx` handles into select instead of borrowing?

**Comment by stjepang** [comment]
That is not possible. But I wonder why you're running into this situation. Do you think it'd be possible to create `Select` on the spot before selection actually happens? Why does it need to be carried inside the struct?

**Comment by tekjar** [comment]
I'm doing that now. But I wasn't sure about the cost of constructing a `Select` object every time

**Comment by stjepang** [comment]
`Select` does allocate memory for the vector of senders/receivers, but it shouldn't be much considering the total cost of selection. It also randomly shuffles the vector every time `select()` (and other similar methods) is called.

**Comment by tekjar** [comment]
Great. I'll just do that. Thanks for the response and the library :)
