### ISSUE TITLE
tick() hanging on Windows

### ISSUE THREAD

**Issue by jfro** [crossbeam-rs/crossbeam#397]
Ran into `tick()` not working properly on Windows. Seems to hang `select!{}` except an occasional run of the binary would see a tick fire.

Example code used below, works on macOS & Rust playground, on windows it times out a few times & then hangs:

```Rust
use crossbeam_channel as chan;
use std::time::{Duration, Instant};
fn main() {
    let x = chan::tick(Duration::from_millis(50));
    let mut i = 0;
    while i < 10 {
        chan::select! {
            recv(x) -> msg => { i += 1; println!("{} {:?}", i, msg);  },
            default(Duration::from_millis(10)) => {  println!("timeout");  },
        }
    }
}
```

This also hangs, no `select!` used:
```Rust
use std::time::{Duration, Instant};
use crossbeam_channel::tick;

fn main() {
    let start = Instant::now();
    let ticker = tick(Duration::from_millis(100));

    for _ in 0..5 {
        ticker.recv().unwrap();
        println!("elapsed: {:?}", start.elapsed());
    }
}
```

**Comment by jfro** [comment]
I apologize, left out that I'm using crossbeam-channel 0.3.8.

Looks like this might be fixed in `master`? Testing the non-select snippet above successfully so far.

**Comment by mchesser** [comment]
Yeah this is this issue: https://github.com/crossbeam-rs/crossbeam/issues/388

**Comment by jfro** [comment]
closing since it's fixed in master, thanks!
