### ISSUE TITLE
What's the recommended usage of Deque?

### ISSUE THREAD

**Issue by dominikbraun** [crossbeam-rs/crossbeam#399]
This is a question, not any feature proposal or bug issue.

So I do understand the principles behind a work-stealing deque and know how the Injector, Workers and Stealers usually interact with each other. However, I'm a bit confused about the usage of the `deque` library.

In my understanding (and it is described so in the crate documentation), there is one global `Injector` queue which takes all tasks. In each thread, there is one `Worker` queue. Each worker pops tasks from its queue, and if it is empty, it takes a task from the global `Injector`.

- Does the worker access the global queue exclusively with `steal_batch()`? If so, is "steal" the correct term here?
- `steal_batch()` takes a reference to a `Worker`, but each worker runs in an own thread. Does that mean that the `Injector` has to be cloned to be accessable from each thread?
- Is there any complete usage example available, following the best practises to use this crate?

Many thanks in advance :)

**Comment by dominikbraun** [comment]
Anyone? :D

**Comment by dominikbraun** [comment]
D:

**Comment by stjepang** [comment]
I suggest looking at `async-std`'s current scheduler implementation. It's pretty small :)

https://github.com/async-rs/async-std/blob/b3d30de4a11d785929a086e458ec1da4aec34bf3/src/task/executor/pool.rs
