### ISSUE TITLE
Unable to use select macro in #![forbid(unsafe_code)] environments

### ISSUE THREAD

**Issue by karroffel** [crossbeam-rs/crossbeam#405]
## Description

I am using `#![forbid(unsafe_code)]` in my crate and for a while I only had a single `recv()` inside of a select macro and everything was compiling fine.

When I added a second `recv()` arm it failed to compile.

I switched to using the `Select` struct for now and it compiles and works properly.

I expected the `select!` macro to only use the safe API of `Select`, not emitting unsafe code inside the macro.

## Example code

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=efee4be440204c5c160827d5fa1de5fb

**Comment by taiki-e** [comment]
if the macro is fully safe, I think we should remove `#[allow(unsafe_code)]`.
https://github.com/crossbeam-rs/crossbeam/blob/ae148dec8eff2ee40dc4d6c11ae63d79bfd79b6e/crossbeam-channel/src/select_macro.rs#L925

On the other hand, if the macro is not safe, it seems reasonable to use `#[allow(unsafe_code)]` (prevents unsafe macros from being used on the crate that uses `#![forbid(unsafe_code)]`).

(The current behavior of lint is a little odd, see https://github.com/rust-lang-nursery/pin-utils/issues/2 for related discussion.)

**Comment by extrawurst** [comment]
I stumbled on this aswell. what can be done about it? I end up using `Select` manually instead of the macro because that works fine with `#![forbid(unsafe_code)]` - the least would be to document this.
