### ISSUE TITLE
channel::tick() behavior questions

### ISSUE THREAD

**Issue by theof** [crossbeam-rs/crossbeam#406]
Hello !
When using `channel::tick::recv()` I expected it to compute its time to sleep with some kind of `Instant` saved at the time of the `Channel` instantiation.
Instead the `Instant` used is the one taken from the last message received, which has two effects :
- it guarantees that the specified duration at least elapses between two messages received
- it leads to a small shift from the initial `Channel` instantiation Instant, mostly due to the job scheduler not waking up the thread necessarily on time

If this was intended originally, then some documentation about the second effect is necessary.
If this is a bug, I would be happy to send a PR. However we must keep in mind that some users might rely on the first effect above.

_Also, I think the `channel::tick::recv` should not have to loop around a `thread::sleep` as the latter already guarantees to sleep **at least** the provided duration, which leaves room for simplifying this file a lot._

**Comment by drrlvn** [comment]
Until I read this issue I had the same expectation of `tick()` as you did but after reading the code I think you're right.

IMO The time it takes to handle a message should not cause the time the next one is delivered to be shifted.

**Comment by theof** [comment]
Maybe we should bring that discussion to https://github.com/crossbeam-rs/rfcs ?

**Comment by stjepang** [comment]
The next message delivery time is always `max(last_delivery, now) + duration`.

You're right that there is some unnecessary drift due to the way `recv()` is implemented. I submitted a fix in #456.
