### ISSUE TITLE
Invalid license identifiers

### ISSUE THREAD

**Issue by Mossop** [crossbeam-rs/crossbeam#419]
The license identifiers found in the Cargo.toml look like `MIT/Apache-2.0` and `MIT/Apache-2.0 AND BSD-2-Clause` but `/` is not valid in SPDX. I'm assuming that `MIT OR Apache-2.0` is what is intended. I'd provide a pull request but I'm not sure whether the BSD case needs to be `(MIT OR Apache-2.0) AND BSD-2-Clause` or `MIT OR Apache-2.0 AND BSD-2-Clause`

**Comment by stjepang** [comment]
I believe it should be `(MIT OR Apache-2.0) AND BSD-2-Clause`
