### ISSUE TITLE
Non-GC implementation

### ISSUE THREAD

**Issue by Ujang360** [crossbeam-rs/crossbeam#420]
Can we have a non-GC implementation? I want to understand the challenge.

**Comment by jeehoonkang** [comment]
Would you please elaborate your question?  It's open-ended, and I'd like you to narrow down the meaning of your question.

**Comment by Ujang360** [comment]
I'm building a realtime system, and when I notice that `Crossbeam` uses GC, I'm wondering why it needs one.

Or maybe I was wrong about GC. But the question remains the same, can we have a non-GC implementation of `Crossbeam`?

**Comment by Ujang360** [comment]
Nevermind, thanks @jeehoonkang :+1:

**Comment by jeehoonkang** [comment]
All pointer-based nonblocking data structures need a garbage collector, which may be a lot less sophisticated than JVM or .NET GC but still be at least (semi-)automatic.  This blog post nicely describes the reason: http://aturon.github.io/tech/2015/08/27/epoch/#the-problem

So the choices are (1) implementing a GC, or (2) giving up lock-freedom and implementing blocking data structures.
