### ISSUE TITLE
Send message to a specific thread

### ISSUE THREAD

**Issue by bcashier** [crossbeam-rs/crossbeam#421]
Hi

Is there any clear example on how to send a message to a specific thread ?

Clearely, I want a function inside a thread that listen live messages received from the main function of my script on user request, this mean each time a request is receive from online user, I send it to the specific thread were the function is working.

Just a small example that interpret this case please, I am stcuking since I am new to channels ad can't find a good example that demonstrating how it works.

Thanks again

**Comment by Vtec234** [comment]
Perhaps [this example](https://doc.rust-lang.org/rust-by-example/std_misc/channels.html) could be helpful? It illustrates `std` channels rather than Crossbeam channels, but they operate on similar principles.

**Comment by bcashier** [comment]
@Vtec234 Thank you sir ! Yes, I had only to switch from `mpsc` to `crossbeam`.

Thank you
