### ISSUE TITLE
crossbeam-epoch: Storing a `Guard` in TLS may be unsound

### ISSUE THREAD

**Issue by oliver-giersch** [crossbeam-rs/crossbeam#422]
I've noticed that `Guard`s store a raw `*const Local` pointer to the thread local state.

When storing a `Guard` in TLS, however, it is possible that the thread's `LocalHandle` is dropped before the guard. This marks the `Local` to be removed from the global list of locals, so another thread could potentially remove the `Local` and destroy it, before the `Guard` dereferences the raw pointer in its own `drop()` function.

At least that is my understanding.

```rust
use std::thread;

extern crate crossbeam_epoch;

use crossbeam_epoch::{self as epoch, Guard};

thread_local!(static GUARD: Guard = epoch::pin());

fn main() {
    thread::spawn(move || {
        GUARD.with(|_| println!("thread pinned"));
    })
    .unwrap().join().unwrap();
}
```

I've also added `println`s to the `Drop` impls of `Guard` and `LocalHandle`, which produces the following output (the second guard drop message is due to an internally created guard being dropped):

```
thread pinned
dropping local handle
dropping guard
dropping guard
```

**Comment by stjepang** [comment]
That looks like a bug. Every `Guard` bumps a reference count in `Local`, which means `LocalHandle` should not be dropped before all `Guard`s referencing it get dropped.

**Comment by jeehoonkang** [comment]
We can fix this by either (1) guaranteeing `LocalHandle` doesn't drop before all `Guard`s do, or (2) don't allow guards in TLS in the API.  I prefer (2) because guards are meant to be short-lived...

**Comment by oliver-giersch** [comment]
> That looks like a bug. Every `Guard` bumps a reference count in `Local`, which means `LocalHandle` should not be dropped before all `Guard`s referencing it get dropped.

I have to stand corrected, only after going over it again I realized that the `LocalHandle` is dropped (due to TLS destruction) first, but doesn't call `finalize` due to there still being an active guard.
Only when the guard itself is dropped is the `Local` actually finalized and marked for removal from the global thread list.

The full picture of the sequence is this:
```
thread pinned
dropping local handle
dropping guard
finalizing local
dropping guard
```

Which appears to be correct, so I apologize for the false report.
