### ISSUE TITLE
AtomicCell without lock for non-usize values in stable.

### ISSUE THREAD

**Issue by manuthambi** [crossbeam-rs/crossbeam#423]
Now that `std::atomic::AtomicU{8,16,32,64}` has been stabilized, please allow `AtomicCell` to store values with non-`usize` widths without a lock. 

This would require increasing the min rust version. Let me know if you like me to send a pull request.

Thanks.

**Comment by manuthambi** [comment]
Ah, we are waiting for `cfg(target_has_atomic)` to be stabilized, I guess?

**Comment by stjepang** [comment]
Honestly, I would just use those non-usize atomic types. Platforms on which they don't exist are niche anyway...

**Comment by manuthambi** [comment]
@stjepang, I created pull request #454. I had to use `cfg(target_pointer_width)` on stable to make the CI pass. The code can be cleaned up later when `cfg(target_has_atomic)` is stabilized. 

I don't quite understand why dependency tree check is failing now. Anyways, we need a new release (with breaking change), and that would most likely fix the dependency tree check issue.

**Comment by manuthambi** [comment]
The dependency tree check was failing because we needed cfg-if version 0.1.10 instead of 0.1.2. Fixed that.

**Comment by manuthambi** [comment]
I reworked the patch to use autocfg crate. The code is cleaner and we don't need the MSRV bump anymore.
