### ISSUE TITLE
crossbeam-channel deadlock when used in separate dlls

### ISSUE THREAD

**Issue by Visic** [crossbeam-rs/crossbeam#424]
Waiting on the receive of a channel in a dynamically loaded library deadlocks.

Minimum reproducible example: [git repo](https://github.com/Visic/crossbeam-dll-test)

Things I have confirmed:

1. park/unpark work correctly between dll's
2. send/recv work correctly within the process (without the external dll)
3. the standard channel (std::sync::mspc) works correctly
4. this deadlock occurs in both the latest release (0.3.9) as well as the master

**Comment by Chopinsky** [comment]
Do your library / dll use `future` or `async` features? I've heard of several reports where using `crossbeam-beam's` channel in `poll` will cause deadlock.

**Comment by Visic** [comment]
It doesn't use those features directly.

This is the entire dll code
```
#[no_mangle]
pub fn start(receiver: crossbeam_channel::Receiver<i32>) -> std::thread::JoinHandle<()> {
    std::thread::spawn(move || {
        println!("{:?}", receiver.recv());
    })
}
```


I simply load the dll using libloading, and call the start function passing it a channel to listen to.

**Comment by stjepang** [comment]
@Visic Do you think this could have something to do with the initialization of TLS when the DLL is loaded?

**Comment by Visic** [comment]
It doesn't seem to be the TLS, I tried hacking away at the crossbeam channel code to remove it all and the deadlock still occurred. I may have broken some logic in the process and introduced a look-a-like bug, but it doesn't seem like it.

After a bit of debugging, it seems like it is getting stuck in the context.rs file, specifically "thread::park()" on line 175. Commenting that out just causes an infinite loop because the "Selected" on line 156 is always "Waiting".

**Comment by Visic** [comment]
Progress! After finally getting back around to this, the difference between the runtime loaded dll and the same library loaded statically, is apparently the thread id.

Line 86 in waker.rs:
if self.selectors[i].cx.thread_id() != thread_id

It's true in the static lib, but always false in the runtime loaded one.

**Comment by Visic** [comment]
Ok, I found it, the bug is in the standard library's creation of thread id's. They use a local static variable as a counter for the id which winds up being an entirely different instance in the dll causing the id's to start over!

**Comment by Visic** [comment]
Just to follow up in case anyone has this problem, the issue with the thread id's is deemed "not a bug" in the standard library as the configuration of my library and application is not a supported one. Specifically, the way my project was configured causes multiple instances of the standard library to be included, each of which will have their own instance of any static state.

My solution was just to force the standard library to be dynamically linked into everything using the "-C prefer-dynamic" in the [build] section of my .cargo/config, as well as changing my "cdylib" to "dylib". However, a word of warning, this works for x86_64-pc-windows-msvc and armv7-unknown-linux-gnueabihf because both of those include a shared library version of the standard library, some distributions do not, so you would need to compile it yourself (possibly using xargo).
