### ISSUE TITLE
More complete implementation of CachePadded

### ISSUE THREAD

**Issue by tinco** [crossbeam-rs/crossbeam#427]
Hi, I'm not sure if more platforms are interesting to you, but I've made a slightly more complete implementation of padding a struct to the cache line size here:

https://github.com/tinco/cache_line_size

I got the information on the cache line sizes from the Go compiler repository, so I'm pretty sure these are correct for all platforms Go runs on, which is a whole bunch.

**Comment by stjepang** [comment]
Thank you! :) It would be great to have those in our `CachePadded`

**Comment by novacrazy** [comment]
Something else to keep in mind is the difference in cache line size between Intel and AMD. 

`znver1` and `znver2` are the target-cpu values for Zen 1 and Zen 2 AMD CPUs, and I think they have slightly smaller cache line sizes than modern Intel CPUs.
