### ISSUE TITLE
const AtomicCell::new

### ISSUE THREAD

**Issue by Arnaz87** [crossbeam-rs/crossbeam#439]
Is there a reason for it not being const? UnsafeCell::new is already const, but it is unsafe so I don't know if there's any reason for Atomic not being const

**Comment by taiki-e** [comment]
AtomicCell::new is now const fn in #437.

**Comment by Arnaz87** [comment]
nice, just in time

**Comment by Arnaz87** [comment]
Wait, why is it behind a feature?

**Comment by taiki-e** [comment]
> Wait, why is it behind a feature?

The minimum supported version of crossbeam is Rust 1.28, but const fn requires Rust 1.31. So `AtomicCell::new` becomes const fn [in Rust 1.31 or later.](https://github.com/crossbeam-rs/crossbeam/pull/437/files#diff-a92c9e0ee1515d6b29ca1f9228c96805R5-R6)
