### ISSUE TITLE
crossbeam-channel segfault on android arm64-v8a emulator

### ISSUE THREAD

**Issue by fredszaq** [crossbeam-rs/crossbeam#440]
Hi! After a cargo update on a large project I started seeing segfaults on in test run on an android `arm64-v8a` emulator. These segfaults seems to come from `crossbeam-channel` as downgrading to `0.3.8` removes the problem.

I started poking around in order to get a reproduction test case and ended up founding that running a simple `cargo test` on crossbeam-channel on the emulator ends up in a segfault. This seems to happen both on `0.3.8` and `0.3.9` though, but only appears when running the tests on release mode, which smells a lot like a race condition somewhere (probably exacerbated by the fact that the arm64-v8a emulator is slooow). I didn't manage to reproduce it on a real device, having it happen on the emulator is problematic though as is is way easier to setup for continuous integration than a device.

The test [`select_macro::linearizable_default`](https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-channel/tests/select_macro.rs#L732) seems to trigger the segfault most of the time when running in release.

## Steps to reproduce:
1. get the android ndk https://developer.android.com/ndk/downloads 
2. get the android sdk tools https://developer.android.com/studio#downloads (bottom of page) and use `sdkmanager` to install the packages `platform-tools` `tools` `system-images;android-24;default;arm64-v8a` (you need to add `adb` in `android-sdk/platform-tools` to you path for dinghy do work)
3. install [dinghy](https://github.com/snipsco/dinghy) with `cargo install cargo-dinghy` (cross compilation helper)
4. setup an android emulator `android-sdk/tools/bin/avdmanager create avd -n foobar -k 'system-images;android-24;default;arm64-v8a' -b arm64-v8a -c 256M -d 7 -f`
5. start the emulator `android-sdk/emulator/emulator -avd toto -prop emu.uuid=toto -partition-size 2048 -no-snapshot -no-window -wipe-data -cores 6 -memory 4096`
6. run the tests `ANDROID_NDK_HOME=/path/to/ndk cargo dinghy --platform auto-android-aarch64-api24 test -p crossbeam-channel  --test select_macro --release -- linearizable_default`

**Comment by stjepang** [comment]
Could you perhaps check if the problem persists if you use the latest `crossbeam-channel` from the `master` branch?

**Comment by fredszaq** [comment]
@stjepang yes I also have this on master

**Comment by stjepang** [comment]
I followed the reproduction instructions but I'm stuck at step 6:

```
$ ANDROID_NDK_HOME=/home/stjepang/work/android/ndk cargo dinghy --verbose --platform auto-android-aarch64-api24 test -p crossbeam-channel --test select_macro --r
elease -- linearizable_default
 DEBUG dinghy_lib::android > ADB found: "/home/stjepang/work/android/platform-tools/adb"
 DEBUG dinghy_lib::android > Android NDK: "/home/stjepang/work/android/ndk"
 ERROR cargo_dinghy        > Error: No such file or directory (os error 2)
```

Any idea what the problem might be?

**Comment by stjepang** [comment]
One more piece of information that would be helpful is checking whether the problem is with bounded, unbounded, or both types of channel.

Here you can change `0..2` to `0..1` for bounded and to `1..2` for unbounded channels:

https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-channel/tests/select_macro.rs#L739

**Comment by stjepang** [comment]
Here's with `-vvv`:

```
$ ANDROID_NDK_HOME=/home/stjepang/work/android/ndk cargo dinghy -vvv --platform auto-android-aarch64-api24 test -p crossbeam-channel --test select_macro --release -- linearizable_default
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/work/crossbeam/dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/work/crossbeam/.dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/work/crossbeam/.dinghy/dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/work/crossbeam/.dinghy/.dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/work/dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/work/.dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/work/.dinghy/dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/work/.dinghy/.dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/.dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/.dinghy/dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/stjepang/.dinghy/.dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/.dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/.dinghy/dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/home/.dinghy/.dinghy.toml"
 TRACE dinghy_lib::config > No configuration found at "/.dinghy.toml"
 DEBUG dinghy_lib::android > ADB found: "/home/stjepang/work/android/platform-tools/adb"
 DEBUG dinghy_lib::android > Android NDK: "/home/stjepang/work/android/ndk"
 ERROR cargo_dinghy        > Error: No such file or directory (os error 2)
```

**Comment by fredszaq** [comment]
seems the file searched is the `source.properties` in the ndk dir, do you point to the good dir in the environment variable (ie  the one containing the `source.properties`)

**Comment by kali** [comment]
FWIW, we have just improved this error message and release cargo-dinghy as 0.4.17 .

**Comment by stjepang** [comment]
Seems like something is wrong with the compiler or the android environment.

If you replace the contents of `select_macro.rs` with the following, it still segfaults:
https://gist.github.com/stjepang/c21e9ac485fd97b19554e5cee72a19c0

But note that this file has no unsafe code! That means something unrelated to `crossbeam` is very broken. Not sure what exactly :/

**Comment by fredszaq** [comment]
hum indeed, further reducing you gist gives me something like that
```rust
#[test]
fn foobar() {
    struct Foo {
        _u1: u64,
        _u2: u64,
        _u3: Box<u64>,
    }
    for _ in 0..100 {
        let foobar = Box::into_raw(Box::new(Foo {
            _u1: 1,
            _u2: 1,
            _u3: Box::new(1),
        }));
        println!("{:p}", foobar);
    }
}
```
that still segfaults...
