### ISSUE TITLE
Apache license is not filled out

### ISSUE THREAD

**Issue by Darksonn** [crossbeam-rs/crossbeam#441]
See the following snippet:

https://github.com/crossbeam-rs/crossbeam/blob/f54db88d1a66eea8338176ae288b91a26764f7b7/LICENSE-APACHE#L188-L190

Compare to:

https://github.com/crossbeam-rs/crossbeam/blob/f54db88d1a66eea8338176ae288b91a26764f7b7/LICENSE-MIT#L2-L4

**Comment by taiki-e** [comment]
If I understand correctly, that is a template for how to apply the Apache License to your work. (see also https://github.com/rust-lang/rust/issues/52236#issuecomment-404149394 and https://github.com/rust-lang/rust/pull/43498)

https://github.com/crossbeam-rs/crossbeam/blob/f54db88d1a66eea8338176ae288b91a26764f7b7/LICENSE-APACHE#L176-L189

**Comment by stjepang** [comment]
I have filled out the missing parts in `LICENSE-APACHE` 26 days ago and forgot to close this issue :)
