### ISSUE TITLE
Crossbeam-channel release including clippy fixes

### ISSUE THREAD

**Issue by gterzian** [crossbeam-rs/crossbeam#443]
Would it be possible to do a release that includes the below commit? Looks like `0.3.9` just missed it...

https://github.com/crossbeam-rs/crossbeam/commit/c725403c9b4c28e1f5e9a35849c236f1b34f67cc

**Comment by stjepang** [comment]
New version has been published now :)

**Comment by gterzian** [comment]
Thanks!
