### ISSUE TITLE
Question: Why look like bounded(0) not block using dbg!?

### ISSUE THREAD

**Issue by mamcx** [crossbeam-rs/crossbeam#445]
I try to emulate a [streaming protocol using channels instead of iterators](https://www.reddit.com/r/rust/comments/dqtvst/is_possible_to_use_channels_and_to_do_imperative/) (so get a way to do pseou-coroutines):

```rust
use crossbeam::crossbeam_channel::unbounded;

fn main() {
    let (s, r) = bounded(0);

    thread::spawn(move || {
        dbg!("s1");
        s.send(1).unwrap();
        dbg!("s2");
        s.send(2).unwrap();
        dbg!("s3");
        s.send(3).unwrap();
        dbg!("end");
        drop(s); // Disconnect the channel.
    });
    for x in r.iter() {
        dbg!(x);
    }
}
```
I expect to see in order:

> s1, 1, s2, 2, etc...

but the output is different, like:
```
[src/main.rs:59] "s1" = "s1"
[src/main.rs:69] x = 1
[src/main.rs:61] "s2" = "s2"
[src/main.rs:63] "s3" = "s3"
[src/main.rs:69] x = 2
[src/main.rs:69] x = 3
[src/main.rs:65] "end" = "end"
```

**Comment by caelunshun** [comment]
You have a race condition: there's no synchronization between when you send/receive a value and make the call to `dbg!()`. In your case, here's the sequence of events (pseudocode):

```rust
Thread 1: dbg!("s1")
Thread 1: s.send(1).unwrap()
Thread 2: let x = r.recv();
Thread 2: dbg!(x); // 1
Thread 1: dbg!("s2");
Thread 1: s.send(2).unwrap();
Thread 2: let x = r.recv();
Thread 1: dbg!("s3");  // Problem starts here: no order guaranteed between operations in threads!
Thread 2: dbg!(x); // 2
Thread 1: s.send(3);
Thread 2: let x = r.recv();
Thread 2: dbg!(x); // 3
...
```

So the problem is not an issue with crossbeam's channels.

**Comment by mamcx** [comment]
Ok, so how I can do a streaming of data? Or is crossbeam not the tool for it?

**Comment by caelunshun** [comment]
Well, everything should still work as expected, except that side effects won't be noticed in a defined order. If you want to have a thread sending data and another processing it, that will work fine as long as you don't have the sender relying on updates made by the receiver.
