### ISSUE TITLE
On send, report transition from 0 to 1 elements in channel

### ISSUE THREAD

**Issue by uazu** [crossbeam-rs/crossbeam#461]
The use-case is as follows. There is one main thread which is waiting on I/O (e.g. mio), and there are many other threads which might want to schedule some work to run in the main thread. So I need an unbounded queue or channel from those threads to the main thread. However to get the main thread to pay attention, I need some I/O event, e.g. Waker in mio 0.7, or sending a byte on a UNIX pipe.

So on a transition from 0 to 1 elements, I need to send that 'wake' signal. On transition from 1 to 2 etc, I don't need to because the signal is "in the air" still. So the problem is how to detect a 0 to 1 transition in crossbeam. If I test `is_empty` before doing the send, that is a race. It could go: length 1, sending thread checks is_empty, main thread receives, length goes to 0, sending thread sends. In this case the sending thread doesn't notice the 0-1 transition and doesn't signal the 'wake', and so stuff gets stuck in the queue.

Can you see a way that I can do this in crossbeam right now? Or do you consider that this is a feature you'd be interested in adding? If not, I'll close this and look for another solution. Thanks!

**Comment by stjepang** [comment]
There is not a way to do that with channels. What if you had an `Arc<AtomicBool>` named `is_woken` that is shared between all threads? The main thread sets it to `false` whenever it wakes up. Other threads set it to `true` right after sending a message and wake the main thread depending on its previous value:

```rust
sender.send(message).unwrap();

if is_woken.swap(true) == false {
    wake_main_thread();
}
```

What do you think?

**Comment by uazu** [comment]
Thanks. Yes, I was starting to think along those lines. But it seems like duplicating information and functionality. I'm happy to go with that solution, though.

This whole thing has thrown up a number of questions for my implementation so I will need to experiment with a few different approaches.

I will close this ticket. Thanks for the help.
