### ISSUE TITLE
[bug] Reading uninit memory

### ISSUE THREAD

**Issue by xacrimon** [crossbeam-rs/crossbeam#467]
Uh it looks like something is reading uninit memory. MSan is screaming about it anyway.
Here is a link to the failing CI job about it: https://github.com/xacrimon/dashmap/runs/433027911

It contains the MSan output.

**Comment by cynecx** [comment]
So the issues lies somewhere in `crossbeam-utils`' build-script. Without a proper backtrace it's probably hard to say, however I would assume that this might be false-positive somehow.

**Comment by xacrimon** [comment]
Yep, I'm gonna see if I get can a backtrace.

**Comment by Shnatsel** [comment]
Normally you need to exclude build scripts from running with sanitizers, like so:

`RUSTFLAGS="-Z sanitizer=$SAN" cargo run --target x86_64-unknown-linux-gnu`

Memory Sanitizer is extra tricky and also requires you to rebuild ALL linked code with it, including the standard library. See https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html for details
