### ISSUE TITLE
[bug] [undefined behaviour] Use of `mem::uninitialized()`

### ISSUE THREAD

**Issue by xacrimon** [crossbeam-rs/crossbeam#468]
Seems to occur in `crossbeam-epoch`.

Full MIRI output is here: https://github.com/xacrimon/dashmap/runs/433047062.

**Comment by cynecx** [comment]
https://github.com/crossbeam-rs/crossbeam/pull/458 should probably fix this.

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rust/pull/66059, this UB [leads to a segfault](https://github.com/rust-lang/rust/pull/66059#issuecomment-586862124). It would be great to get a fixed version of crossbeam-epoch released.

**Comment by xacrimon** [comment]
@RalfJung according to @cynecx this should be fixed on master now. Care to try again?

**Comment by RalfJung** [comment]
Yes it is fixed on master.

**Comment by xacrimon** [comment]
Alright. I will keep this issue open until a release is made.
