### ISSUE TITLE
Multiple versions for dependency `autocfg`

### ISSUE THREAD

**Issue by ArekPiekarz** [crossbeam-rs/crossbeam#472]
#### Summary
Latest release of crossbeam-utils (0.7.0) depends on an old version of autocfg, which triggers the following Clippy warning when used together with other packages and slows down compilation:
```
warning: multiple versions for dependency `autocfg`: 1.0.0, 0.1.7
  |
  = note: `-W clippy::multiple-crate-versions` implied by `-W clippy::cargo`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#multiple_crate_versions
```
The version from git already depends on `autocfg 1`, so it seems it could be fixed by just releasing a new version of crossbeam-utils - the last one is 3 months old.

#### Steps to reproduce
Add these dependencies to your project:
dirs 2.0.2, which depends on dirs-sys -> redox_users -> rust-argon2 -> **crossbeam-utils -> autocfg 0.1.7**
rust-ini 0.15.1, which depends on ordered-multimap -> **hashbrown -> autocfg 1**

Run: `cargo clippy`

**Comment by taiki-e** [comment]
Fixed in #460
