### ISSUE TITLE
Publish new releases of crossbeam crates

### ISSUE THREAD

**Issue by jonhoo** [crossbeam-rs/crossbeam#473]
We currently have a couple of open issues that are resolved on master (like #472 and #468), and some important fixes that have landed (like #466 and #458). It'd be great to push out a new release of the various crossbeam crates to get those to users. What currently stands in the way of doing so? Can the next batch of releases all be point releases, or is a breaking release necessary?

What are the next steps, and is there any way in which I can help?
/cc @stjepang @jeehoonkang

**Comment by jeehoonkang** [comment]
Sorry for late response.  May I ask if you could make a PR that creates a new version, which should look like #444?  Then I'll merge immediately and release Crossbeam at crates.io.

**Comment by jonhoo** [comment]
Will do!

**Comment by jonhoo** [comment]
@jeehoonkang submitted https://github.com/crossbeam-rs/crossbeam/pull/474
