### ISSUE TITLE
channel: ready::fairness2 test is racy

### ISSUE THREAD

**Issue by jonhoo** [crossbeam-rs/crossbeam#477]
The test occasionally [fails in CI](https://travis-ci.org/crossbeam-rs/crossbeam/jobs/651567571#L538) and [locally](https://github.com/crossbeam-rs/crossbeam/pull/474#issuecomment-589250957).

Reproduce by running:
```console
$ for (( i=1 ;; i+=1 )); do echo "*** test $i ***"; cargo test --test ready fairness || break; done
```

To quote @cuviper:

> It seems to fail even more frequently with `--release`, so maybe the test just needs more allowance?

**Comment by stjepang** [comment]
Hmm yeah that definitely looks like a fluke - statistically speaking, the test is *bound* to fail :)  (but we hope so rarely it never actually fails). I think bumping the threshold should do the trick.

**Comment by jonhoo** [comment]
I tried changing the assertion to
```rust
assert!(hits.iter().all(|x| x.get() > 0));
```
And unfortunately even that sometimes fails. I guess we'd have to increase the count?

**Comment by jonhoo** [comment]
I opened https://github.com/crossbeam-rs/crossbeam/pull/495 with the updated assertion and an increased `COUNT`, and that seems to not be racy for me at least.
