### ISSUE TITLE
Add loom support to crossbeam-epoch

### ISSUE THREAD

**Issue by jonhoo** [crossbeam-rs/crossbeam#486]
It'd be really cool if `crossbeam-epoch` had support for [`loom`](https://github.com/tokio-rs/loom). That would allow us to write more reliable tests where every execution interleaving and atomic visibility case actually gets exercised, without resorting to some of the "spin up a bunch of threads" tests we have today. It would also allow downstream crates to write similar tests on top of `crossbeam-epoch`, such as in `flurry` where we need loom to exercise some tricky [contention cases](https://github.com/jonhoo/flurry/pull/72#issuecomment-610618109) that are hard to hit reliably otherwise.

The loom README has a decent amount of info on how to go about adding loom support, but it _basically_ boils down to using types from `loom` instead of from `std` (or `core`) when `cfg(loom)`. Then, for tests, you just surround the test with `loom::model(|| {})`, and loom will automatically run the closure under different concurrent execution schedules.

/cc @jeehoonkang @carllerche @domenicquirl

**Comment by jonhoo** [comment]
The `sanitize` feature is another example of something that could probably go away if we had loom support.

**Comment by jonhoo** [comment]
One tricky thing we'd have to figure out is how to expose loom support to downstream crates. If we make it a `cfg(loom)` the way the loom docs [suggest](https://github.com/tokio-rs/loom#structuring-tests), then I think we'd have to make `loom` a non-optional dependency since you can't set per-`cfg` dependencies. Alternatively, we just make `loom` a feature (like `sanitize`) — not sure why that's not what the loom docs propose.

**Comment by cynecx** [comment]
Just wondering, does `loom` support `atomic::fence`?

**Comment by jonhoo** [comment]
[Yup](https://docs.rs/loom/0.3.0/loom/sync/atomic/fn.fence.html), though not `compiler_fence`.
