### ISSUE TITLE
Async crossbeam_channel::Receiver

### ISSUE THREAD

**Issue by kirs** [crossbeam-rs/crossbeam#501]
I apologize if this was asked in the past. A quick search across existing issues didn't find anything.

[crossbeam_channel::Receiver#recv](https://docs.rs/crossbeam-channel/0.4.2/crossbeam_channel/struct.Receiver.html#method.recv) is a blocking way to receive a message from the channel.

Is there an `async` version of a similar function to make it work with async/await?

If not, does crossbeam plan to support async/await in the future?

**Comment by stjepang** [comment]
There is no plan to support async/await. However, an async channel being prototyped in https://github.com/stjepang/piper

**Comment by jcaesar** [comment]
It seems piper is gone. Would smol's [async-channel](https://github.com/smol-rs/async-channel) do?

**Comment by taiki-e** [comment]
> Would smol's [async-channel](https://github.com/smol-rs/async-channel) do?

Yes, piper has been replaced by async-channel.

**Comment by huntc** [comment]
> There is no plan to support async/await. However, an async channel being prototyped in https://github.com/stjepang/piper

Is there a document/issue/PR that expands on the rationale for having no plans to support async/await? Thanks.

**Comment by taiki-e** [comment]
I've already been involved in maintaining asynchronous channels in 3 projects (futures, tokio, async-channel). And (IIRC) the channels provided by tokio and async-channel are efficient enough. So, there is no motivation to do this in crossbeam.

**Comment by huntc** [comment]
> I've already been involved in maintaining asynchronous channels in 3 projects (futures, tokio, async-channel). And (IIRC) the channels provided by tokio and async-channel are efficient enough. So, there is no motivation to do this in crossbeam that is a library intended for use in sync, not async.

Thanks for the explanation!
