### ISSUE TITLE
CI failure due to SIGSEGV

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam#514]
https://github.com/crossbeam-rs/crossbeam/runs/702734820#step:5:103
https://github.com/crossbeam-rs/crossbeam/runs/702730520#step:5:107

It seems to lurk up from time to time.  I guess it's maybe due to a recently merged PR?  (I'm suspicious of #416, but not 100% sure about this.)

**Comment by jeehoonkang** [comment]
https://github.com/crossbeam-rs/crossbeam/runs/702745639 another failure w/ address sanitizer

**Comment by stjepang** [comment]
It could be - can you check if the issue is present of we revert #416?
