### ISSUE TITLE
Mark `AtomicCell::is_lock_free()` as const fn?

### ISSUE THREAD

**Issue by nyanpasu64** [crossbeam-rs/crossbeam#531]
It would be convenient if I could check if AtomicCells are lock-free at compile time. by marking `AtomicCell<T>::is_lock_free()` as a const fn.

For context, I'm working on an audio program in C++, due to C++ libraries including Qt. In audio programs, taking locks on the audio thread is regarded as unacceptable because it can block and cause the audio to stutter. As a result, I'd like to statically assert that a given atomic type written by the audio thread is lock-free. (I'm mostly looking at Rust for inspiration and comparison, to see whether parts of my code are nicer in C++ or Rust.)

https://github.com/crossbeam-rs/crossbeam/blob/81ab18efc7376f3277a6359fdc20d00b4bcf911c/crossbeam-utils/src/atomic/atomic_cell.rs#L108-L110

calls `atomic_is_lock_free<T>`:

https://github.com/crossbeam-rs/crossbeam/blob/81ab18efc7376f3277a6359fdc20d00b4bcf911c/crossbeam-utils/src/atomic/atomic_cell.rs#L809-L812

expands to the `atomic!` macro:

https://github.com/crossbeam-rs/crossbeam/blob/81ab18efc7376f3277a6359fdc20d00b4bcf911c/crossbeam-utils/src/atomic/atomic_cell.rs#L777-L807

Marking `AtomicCell<T>::is_lock_free()` as `const` doesn't seem to cause issues, but depends on `atomic_is_lock_free`. Trying to mark `atomic_is_lock_free` as `const` fails on https://github.com/rust-lang/rust/issues/49146 "Allow `if` and `match` in constants", and https://github.com/rust-lang/rust/issues/52000 "Allow `loop` in constant evaluation".

From a cursory examination, `atomic!` doesn't truly need a `loop`, but depends on `if`. Note that I don't fully understand `atomic!` nor all call sites.

Are there any plans to mark this as a const fn, to allow users to statically assert it's lock-free? I don't know if `atomic!` needs to be split into two macros or not, with duplication and possible future desynchronization.

**Comment by taiki-e** [comment]
Probably `const_if_match` and `const_loop` will be stable at the same time (https://github.com/rust-lang/rust/pull/72437#issuecomment-644654464), but either way, `atomic!` doesn't really need a loop, so I think it makes sense to conditionally mark `is_lock_free` as a const fn when `const_if_match` is stable.

**Comment by taiki-e** [comment]
Seems stabilization pr has been merged: https://github.com/rust-lang/rust/pull/72437
