### ISSUE TITLE
i need use an  Map struct,Which one should I use?

### ISSUE THREAD

**Issue by zhuxiujia** [crossbeam-rs/crossbeam#532]
i need use an  Map struct,Which one should I use。
the Map struct must impl  Sync and Send,and do not use '&mut self' just like SegQueue

**Comment by xacrimon** [comment]
Crossbeam does not provide this but I happen to do research on this stuff. There are a few libraries available. I've devised benchmarks for all good ones I could gather [here](https://git.acrimon.dev/Acrimon/conc-map-bench). So run the benchmarks and pick whichever you fancy from the list in the readme.

**Comment by zhuxiujia** [comment]
> Crossbeam does not provide this but I happen to do research on this stuff. There are a few libraries available. I've devised benchmarks for all good ones I could gather [here](https://git.acrimon.dev/Acrimon/conc-map-bench). So run the benchmarks and pick whichever you fancy from the list in the readme.

These libraries enforce the use of custom drops.
if crossbeam can support   SyncMap just like golang's SyncMap . 
Even if write is locked, read is unlocked, or GC It's going to be great

**Comment by xacrimon** [comment]
? I don't understand. Everything relies on cust drops. The dashmap library is as close to syncmap as you will get.

**Comment by zhuxiujia** [comment]
> ? I don't understand. Everything relies on cust drops. The dashmap library is as close to syncmap as you will get.

fine
thank you

**Comment by zhuxiujia** [comment]
> ? I don't understand. Everything relies on cust drops. The dashmap library is as close to syncmap as you will get.

find DashMap use RwLock .  my project also use of  tokio.  if  use RwLock it  will be  lock  the runtime.  The best way to do this is to do it lock-free？

**Comment by AngelicosPhosphoros** [comment]
> if use RwLock it will be lock the runtime(may be lock stop all of async task)

You can just run this code on special tokio threadpool for blocking code.

**Comment by zhuxiujia** [comment]
> > if use RwLock it will be lock the runtime(may be lock stop all of async task)
> 
> You can just run this code on special tokio threadpool for blocking code.

But it's not a good idea
