### ISSUE TITLE
Feature request: `recv_deadline`

### ISSUE THREAD

**Issue by Lucretiel** [crossbeam-rs/crossbeam#553]
This is a feature request for an additional `recv` form, `recv_deadline`, for `Recevier` (and an equivalent version for `Sender`). In some use cases, you have an `Instant` to wait for, instead of a `Duration` to wait for, and there's no reason to convert this into a `Duration` when `recv_timeout` will just be converting it *back* into an `Instant`.

**Comment by stjepang** [comment]
This should be easy to implement. Funnily enough, the internal channel implementation actually uses deadlines instead of timeouts, so `recv_timeout()` is implemented as `chan.recv(Some(Instant::now() + timeout))`.

For consistency, it would also be good to then add `send_deadline()`.

**Comment by Lucretiel** [comment]
Cool, I'll work on an impl. I'll see about adding equivalent methods where I can find then.
