### ISSUE TITLE
Nested scopes with lifetime bounds

### ISSUE THREAD

**Issue by joshtriplett** [crossbeam-rs/crossbeam#583]
I'd like to be able to ask a `Scope` object for a nested `scope` whose lifetime is bounded by the lifetime of the outer scope. That would allow a scoped thread to spawn a more narrowly scoped inner thread that can borrow from the outer-scoped thread.

This could look like a method `scope` on `Scope` that creates a new `Scope` with an appropriately bounded lifetime.

**Comment by taiki-e** [comment]
It seems https://github.com/rust-lang/rust/pull/94559 implements this.

**Comment by joshtriplett** [comment]
When I posted the original request, I had a specific use case that motivated it, but it's been too long and I can no longer reconstruct the specific use case. I'm going to close this.

I'm looking forward to the new standard library scopes.
