### ISSUE TITLE
Clarify in documentation when to use queues vs channels

### ISSUE THREAD

**Issue by Rua** [crossbeam-rs/crossbeam#587]
Since these two types both fulfill similar goals, it would be useful to have some advice on which to use when. Specifically, in the situation where the sender and receiver of a channel are both available to a thread. Are particular use patterns faster with one versus the other?

**Comment by taiki-e** [comment]
Depends on the use case, but if you are not sure which to use, it will be preferable in many cases to use channels. Channels have mechanisms to wait efficiently in cases where the channel is not ready. If those mechanisms are not needed, or if you implement them on your own, the queue could be faster than the channel, but depends on the use case or your implementation.
