### ISSUE TITLE
bench should fail with explanation when required `nightly` feature is missing

### ISSUE THREAD

**Issue by pnkfelix** [crossbeam-rs/crossbeam#59]
I just tried grabbing `crossbeam` (I wanted to try to replicate the experimental results from https://aturon.github.io/blog/2015/08/27/epoch/#benchmarks as preparation for an upcoming presentation) and I noticed that out of the box, `cargo run --release --bin bench` just prints a sequence of key value pairs where every value is `0`.

From a quick skim of the code, it appears I was supposed to do `cargo run --features nightly --release --bin bench`; I would recommend that the `bench` program be changed if possible to fail in the scenario where the `nightly` feature is missing, with a message to the user suggesting that they include that feature in the `cargo` invocation.

**Comment by stjepang** [comment]
We don't have `bench` anymore. Closing.
