### ISSUE TITLE
Feature Request: generalizing `CachePadded`

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam#6]
Currently, `CachePadded` only supports datatypes of size <= `CACHE_SIZE`, as far as I understand. Is it possible to generalize `CachePadded` to datatypes of arbitrary size?

**Comment by aturon** [comment]
Not at the moment -- we don't have a way to be generic over an integer used in that way. So probably the best we can do for now is to have a few variants, going up in size.

In the long run, I'd prefer `CachePadded` wasn't necessary -- it should instead be possible to specify minimum alignment preferences directly.

**Comment by whataloadofwhat** [comment]
Could you not use the `#[repr(simd)]` thing further? (nightly only though). E.g:

```rust
#[repr(simd)]
struct Padding(u64, u64, u64, u64, u64, u64, u64, u64); // aligned to 64 bytes
struct CachePadded<T> {
    __val: T,
    __align: [Padding; 0] // forces alignment to match with Padding (at least)
}
```
https://play.rust-lang.org/?gist=236c968f9a6e51107e29&version=nightly

**Comment by jeehoonkang** [comment]
I assume this issue is [resolved in `crossbeam-utils`](https://github.com/crossbeam-rs/crossbeam-utils/blob/master/src/cache_padded.rs#L17): `#[repr(align(64))]` is used in nightly.  Maybe it's too hard to do a similar thing in stable.  I'm closing it!
