### ISSUE TITLE
CachePadded size and alignment

### ISSUE THREAD

**Issue by Aatch** [crossbeam-rs/crossbeam#60]
`CachePadded` seems to massively overestimate the size of a cache line on 64-bit, it's also not clear why the size was chosen.

It seems that the previous estimate of 128-bytes was chosen to avoid interference between adjacent cache lines, but now is assuming a ridiculous 256 bytes due to it being `32 * sizeof(usize)` in the actual structure. Furthermore the reason for picking the sizes isn't stated anywhere, which makes understanding this code frustrating given that almost all CPUs have 64-byte cache lines.

Also the `Padding` struct only aligns to 32-bytes, (4 x 8 (u64) being 32), not the standard 64, which is also confusing.

**Comment by arthurprs** [comment]
This looks like an easy fix. Any objections for making it 64 bytes ?

**Comment by jeehoonkang** [comment]
Actually we cannot make it 64 bytes -- `Participant` is used as an argument for `CachePadded`, but its size is bigger than 64.  Only after generalizing `CachePadded` in such a way that it can serve types bigger than the cache line size, we can make it 64 bytes.

Note that we can make it 128 bytes.

**Comment by arthurprs** [comment]
Could we implement the methods for arrays of cache padding (multiples of 64 bytes but still holding a single T)?

**Comment by jeehoonkang** [comment]
@arthurprs currently we cannot.  See https://github.com/crossbeam-rs/crossbeam/issues/6#issuecomment-142628364 .

**Comment by arthurprs** [comment]
Providing implementations (using macros) for [CachePadding; $$$] up to 4 (256 bytes) should be more than enough.

**Comment by sstewartgallus** [comment]
Why not something along the lines of https://sstewartgallus.com/git?p=uevents-rs.git;a=blob;f=src/cacheline.rs;h=4b726636b02bdc2fbba4e1e7bc3912232864d2b2;hb=HEAD ?
