### ISSUE TITLE
Should park_timeout report the reason for their return (timeout or unpark)?

### ISSUE THREAD

**Issue by taiki-e** [crossbeam-rs/crossbeam#601]
This originally is a breaking change proposed in #563 by @Lucretiel.

We recently released a new minor version of `crossbeam-utils`, so I would prefer not to do the breaking changes right now, but it might make sense to consider doing this in a future version.

**Comment by Lucretiel** [comment]
I have a working version of this feature in https://github.com/Lucretiel/crossbeam/tree/unpark-reason. It's a trivial update to the Parker implementation.
