### ISSUE TITLE
Memory access violation with channels and native library

### ISSUE THREAD

**Issue by kenr** [crossbeam-rs/crossbeam#602]
I have troubles using crossbeam_channel::unbounded in a callback from a native library.
The native library calls the same callback from multiple threads. The callback is a Rust closure that puts the data on a channel. When the sender is invoked a memory access violation happen in rustlib\src\rust\library\core\src\sync\atomic.rs(2370)

I've written an isolated example that trigger the issue:
https://github.com/kenr/channel-native-rs

What may be wrong?

**Comment by taiki-e** [comment]
I think the main issue is [this code](https://github.com/kenr/channel-native-rs/blob/561b799cd4b4c6571aa91b4a9925d13934ac5f18/src/lib.rs#L27-L39).

```rust
pub fn register_callback_safe<C>(mut c: C)
where
    C: Fn(String) + Send + Sync,
{
    let _callback_trampoline = get_callback_trampoline(&c);

    unsafe {
        register_callback(
            _callback_trampoline,
            &mut c as *mut _ as *mut ::std::os::raw::c_void,
        );
    }
}
```

This is registering a reference to `C` that is not guaranteed to live until called. You need to make `C` `'static` or guarantee it in some other way.

https://users.rust-lang.org/t/ffi-callbacks-accessing-outer-variables/48644 is a similar issue, and there are some detailed explanations. I would recommend seeing that.

**Comment by taiki-e** [comment]
> make `C` `'static`

Oh, actually it's not enough to just make `C` to `'static` due to `register_callback_safe` drop `c`. (That's what is actually mentioned in the thread I linked to.)
