### ISSUE TITLE
Seal traits that only intended to be implemented within the crate that defines them

### ISSUE THREAD

**Issue by taiki-e** [crossbeam-rs/crossbeam#620]
Currently, crossbeam provides the following traits:
https://docs.rs/crossbeam/0.8.0/crossbeam/all.html
- [atomic::AtomicConsume](https://docs.rs/crossbeam/0.8.0/crossbeam/atomic/trait.AtomicConsume.html)
- [epoch::CompareAndSetOrdering](https://docs.rs/crossbeam/0.8.0/crossbeam/epoch/trait.CompareAndSetOrdering.html)
- [epoch::Pointable](https://docs.rs/crossbeam/0.8.0/crossbeam/epoch/trait.Pointable.html)
- [epoch::Pointer](https://docs.rs/crossbeam/0.8.0/crossbeam/epoch/trait.Pointer.html)

Some of these seem intended to be implemented for a particular type and not intended to be implemented by the user.
If I understand correctly, the traits below are not intended to be implemented by the user:

- [epoch::CompareAndSetOrdering](https://docs.rs/crossbeam/0.8.0/crossbeam/epoch/trait.CompareAndSetOrdering.html)
  ~~I don't think it makes sense to implement this other than `Ordering` and `(Ordering, Ordering)`.~~
  EDIT: See #621

- [epoch::Pointer](https://docs.rs/crossbeam/0.8.0/crossbeam/epoch/trait.Pointer.html)
  The document says it's a trait for `Owned` and `Owned`.
  > A trait for either `Owned` or `Owned` pointers.

I would prefer to seal these traits using [the sealed trait pattern described in API guidelines](https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed) to prevent them from being accidentally implemented by the user. (Even if we never plan to make breaking changes to these APIs, I believe it's still worthwhile to prevent users from accidentally implementing these traits.)

**Comment by taiki-e** [comment]
- [atomic::AtomicConsume](https://docs.rs/crossbeam/0.8.0/crossbeam/atomic/trait.AtomicConsume.html)
  As the document says, I think this is intended to be implemented for the atomic types of the standard library, but I don't think there is any problem if the user implements this.
  (That said, third-party crates can implement as an inherent method, so I don't think it's a problem to seal it.)

- [epoch::Pointable](https://docs.rs/crossbeam/0.8.0/crossbeam/epoch/trait.Pointable.html)
  cc @jeehoonkang: Is this trait intended to be implemented by the user? (I guess it's "true", but I'm not clear)

**Comment by jeehoonkang** [comment]
- For CompareAndSetOrdering: maybe we can completely switch to `compare_exchange` and always use two orderings for CAS?
  What do you think?

- Pointer: I agree that the sealed trait pattern would be nice for this trait.

- AtomicConsume: I agree that it's "open" to the library users.

- Pointable: it's intended to be implemented by the users who want to precisely control DST and memory layout stuffs.

**Comment by taiki-e** [comment]
> * For CompareAndSetOrdering: maybe we can completely switch to `compare_exchange` and always use two orderings for CAS?
>   What do you think?

Ah, given that the standard library deprecated the methods that use a single ordering for CAS operation, I think it makes sense to remove `CompareAndSetOrdering` trait and change `compere_and_set` to always use two orderings.
