### ISSUE TITLE
Switch from lazy_static to once_cell

### ISSUE THREAD

**Issue by jplatte** [crossbeam-rs/crossbeam#623]
With tokio having switched from lazy_static to once_cell in 0.3, the dependencies on lazy_static are going way down in many of my projects. It would be nice to get rid of it completely in favor of once_cell. Would you be open to a PR?

**Comment by taiki-e** [comment]
I'm the one who [was in favor of this in tokio](https://github.com/tokio-rs/tokio/pull/3187#pullrequestreview-540096230) and I'm in favor of doing this in crossbeam as well. As discussed in https://github.com/tokio-rs/tokio/pull/3187, there are several benefits.

However, I'm not sure how this interacts with loom PR (#487).
cc @jonhoo: Do you think loom can provide API like once_cell's [`Lazy`](https://docs.rs/once_cell/1.5.2/once_cell/sync/struct.Lazy.html)?

**Comment by jonhoo** [comment]
Hmm, I think loom probably could, though it doesn't have such an API today. I think you best bet would be asking over in the tokio Discord in the #loom channel :)

**Comment by taiki-e** [comment]
[Since lazy_static has increased the MSRV to 1.40](https://github.com/rust-lang-nursery/lazy-static.rs/pull/186#issuecomment-838856179), I will do this without waiting for support on the loom side.

**Comment by jonhoo** [comment]
May be valuable to open a bug on the loom side to track that this is a desired feature :)

**Comment by taiki-e** [comment]
filed https://github.com/tokio-rs/loom/issues/263

**Comment by jplatte** [comment]
Any chance we can get new releases of crossbeam-epoch and crossbeam-utils with this?

**Comment by taiki-e** [comment]
Published in crossbeam-epoch 0.9.9 and crossbeam-utils 0.8.9.
