### ISSUE TITLE
Hide loom from dependency graph

### ISSUE THREAD

**Issue by djc** [crossbeam-rs/crossbeam#665]
The way loom is set up now, loom and its dependencies show up in my dep graph as soon as I depend on crossbeam-utils or crossbeam-epoch. It would be nice to avoid this, for example as done in https://github.com/hawkw/sharded-slab/pull/52/files. (I can do the legwork on this if you like.)

**Comment by taiki-e** [comment]
yeah, we plan to do that https://github.com/crossbeam-rs/crossbeam/pull/487#issuecomment-783392692

**Comment by taiki-e** [comment]
(also, it will be downloaded but not actually compiled.)

**Comment by taiki-e** [comment]
will be fixed by #666
