### ISSUE TITLE
crossbeam-utils: test src/cache_padded.rs (line 35) ... FAILED (on armv7hl)

### ISSUE THREAD

**Issue by decathorpe** [crossbeam-rs/crossbeam#668]
```
failures:
---- src/cache_padded.rs - cache_padded::CachePadded (line 35) stdout ----
Test executable failed (exit code 101).
stderr:
thread 'main' panicked at 'assertion failed: addr2 - addr1 >= 64', src/cache_padded.rs:10:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    src/cache_padded.rs - cache_padded::CachePadded (line 35)
test result: FAILED. 110 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 20.39s
```

The same test passes fine with crossbeam-utils 0.8.1, and the only relevant change I see is 1e16fc0. It appears the new heuristics are wrong for 32-bit ARM (armv7-unknown-linux-gnueabihf target).

**Comment by taiki-e** [comment]
We need to fix that test (like https://github.com/crossbeam-rs/crossbeam/pull/641). And it would be nice if 32-bit arm target could be added to CI.

**Comment by taiki-e** [comment]
> it would be nice if 32-bit arm target could be added to CI.

Hmm. cross doesn't run doctest (https://github.com/rust-embedded/cross/issues/225), so cases like this issue cannot be detected by adding 32-bit arm test to CI.

**Comment by taiki-e** [comment]
I found a way to cross-testing doctests -- I will fix this issue as part of https://github.com/crossbeam-rs/crossbeam/pull/801.

**Comment by decathorpe** [comment]
Hum, it looks like the wrong PR closed this issue?
Because this failure is still happening with 0.8.11, or was that fix not pushed in time for that release?

**Comment by taiki-e** [comment]
> was that fix not pushed in time for that release?

Yes. The fix has not been released yet.
