### ISSUE TITLE
Push new minor release of crossbeam-queue

### ISSUE THREAD

**Issue by tweksteen** [crossbeam-rs/crossbeam#702]
Would it be possible to publish a new minor version of `crossbeam-queue` on crates.io? The 33e4c64a change cleaned up the license files. `crossbeam-utils`, `crossbeam-channel` and `crossbeam-epoch` have been released with this change but not `crossbeam-queue`. Thanks.

**Comment by taiki-e** [comment]
Published crossbeam-queue 0.3.2

**Comment by tweksteen** [comment]
Great, thanks!
