### ISSUE TITLE
Custom build command failed.

### ISSUE THREAD

**Issue by HamishWHC** [crossbeam-rs/crossbeam#719]
```
❯ cargo build
   Compiling crossbeam-queue v0.3.2
   Compiling bitflags v1.2.1
   Compiling num-traits v0.2.14
   Compiling atomic v0.5.0
   Compiling proc-macro-nested v0.1.7
error: failed to run custom build command for `crossbeam-queue v0.3.2`

Caused by:
  process didn't exit successfully: `/home/hamishwhc/projects/tournament-infra/api/target/debug/build/crossbeam-queue-3b3201d87437fd2b/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

This error occurred during build of a rocket 0.5/sqlx project. Couldn't find any workarounds for this occurring in crossbeam.

**Comment by taiki-e** [comment]
This is probably a bug in the compiler. Which target are you compiling for?

related: https://github.com/rust-lang/rust/issues/85543, https://github.com/rust-lang/rust/issues/84576, https://github.com/rust-lang/rust/issues/73661, https://github.com/rust-lang/rust/issues/76021, https://github.com/rust-lang/rust/issues/82193, https://github.com/rust-lang/rust/issues/82912

**Comment by HamishWHC** [comment]
Just realised I hadn't tried `cargo clean`. Seems to have fixed it. Sorry to post an issue unnecessarily.
