### ISSUE TITLE
question regarding multiple values - channel

### ISSUE THREAD

**Issue by benydc** [crossbeam-rs/crossbeam#740]
is it possible to send multiple values with `crossbeam-channel` to multi-consumers? If so, are the values each split between consumers?

the `mpsc` can do this, obviously with 1 producer/consumer.

ref: [example here](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/second-edition/ch16-02-message-passing.html#sending-multiple-values-and-seeing-the-receiver-waiting)

**Comment by taiki-e** [comment]
I guess you are talking about broadcast channel: https://users.rust-lang.org/t/using-crossbeam-channels-as-broadcast-channels/31677

**Comment by benydc** [comment]
@taiki-e not really what I wanted, as the broadcast will fan out the value to all consumers, each receiving the same value. I want to achieve something similar to `mqtt protocol`, where the values are sent and then distribute to each consumer.
