### ISSUE TITLE
Old crossbeam-channel could return a crazy length because of integer overflow

### ISSUE THREAD

**Issue by NingLin-P** [crossbeam-rs/crossbeam#749]
In `crossbeam-channel` 0.3.x and 0.4.x (also happen to `crossbeam_queue::SegQueue`), when computing the length of the channel, if the indices fall onto the block end, they will be fixed up by:

https://github.com/crossbeam-rs/crossbeam/blob/48b13dc43cf19e0544d03d16f4b3da3d8b23f076/crossbeam-channel/src/flavors/list.rs#L511-L518

Although the indices have been rotated with `wrapping_sub` previously, if both the head and the tail index are equal to `BLOCK_CAP` here, then `tail -= LAP` will overflow and wrap into `usize::MAX` when build in release mode (or panic when build in debug mode).

https://github.com/crossbeam-rs/crossbeam/commit/1df3ee7b09feabf71d85bac46e36f1eef6257bca has been changed the way to fix up indices, so this problem won't happen on 0.5.x. We may need to cherry-pick this commit to 0.3.x and 0.4.x branches.

**Comment by taiki-e** [comment]
Closing -- Given that the first version of 0.5 that fixed this issue was released over a year ago, the major version is 0, and that there have been few breaking changes between 0.4 and 0.5, there is no motivation to continue maintaining 0.4.
