### ISSUE TITLE
About the Windows environment： no_atomic.rs file

### ISSUE THREAD

**Issue by rockit-ba** [crossbeam-rs/crossbeam#752]
On Windows, the contents of the no_atomic.rs file '.. /no_atomic.rs' cannot compile. how i do?

**Comment by taiki-e** [comment]
You probably need to enable `core.symlinks` in git. (e.g., `git config --global core.symlinks true`)

(If you are using a crate uploaded to crates.io, the symlink should have been converted to a regular file, so I don't think you will have this problem.)

**Comment by rockit-ba** [comment]
yes，you are right
