### ISSUE TITLE
crossbeam-channel panics 'unreachable' on wasm

### ISSUE THREAD

**Issue by namse** [crossbeam-rs/crossbeam#756]
In wasm environment (wasm-unknown-unknown),

I created crossbeam-channel unbounded channel and run 'recv'.
```
let (sender, receiver) = unbounded::<i32>();
receiver.recv();
```
I expected it block and wait until sender.send() called. But immediately it panics with unreachable error.
![image](https://user-images.githubusercontent.com/3580430/145610728-bd49585d-1be8-45bb-a90e-3a97fb46fb63.png)

Is it normal to not be able to block threads in the wasm environment using channel.recv()?

**Comment by taiki-e** [comment]
wasm is single-threaded by default, and some features related to blocking threads are not available. Therefore, this is not unexpected behavior.

If you want to receive values from a channel on wasm, I would suggest using methods that don't block thread such as try_recv or using an asynchronous channel.
