### ISSUE TITLE
Can we abstract threads:  mutex lock,thread_id, sleep, park, unpark, unpark(timeout), and so on? This replaces the Dyn trait to support other libraries such as Tokio and Async_STD

### ISSUE THREAD

**Issue by zhuxiujia** [crossbeam-rs/crossbeam#757]
Can we abstract thread sleep, park, unpark, unpark(timeout), and so on? This replaces the Dyn trait to support other libraries such as ``` tokio```and ``` async_std ```  not blocking the runtime environment

**Comment by taiki-e** [comment]
Both of the libraries you listed are well known for not accepting abstractions that do not have a path to the standard library.

Even if we implement this in crossbeam, it is very unlikely that what you expect will happen.
