### ISSUE TITLE
Pop enum for chase_lev try_pop

### ISSUE THREAD

**Issue by rphmeier** [crossbeam-rs/crossbeam#76]
`steal` returns an enum which signifies whether the steal operation was successful, aborted, or the queue was empty. `try_pop` as it stands only covers the success and failure cases.

**Comment by rphmeier** [comment]
To be consistent with the `Steal` enum, it should be called `Pop` rather than `Popped`

**Comment by jeehoonkang** [comment]
Assuming that the compare-and-swap in `try_pop` is strong (https://github.com/crossbeam-rs/crossbeam/blob/master/src/sync/chase_lev.rs#L206), in the sense that it doesn't fail spuriously (https://doc.rust-lang.org/beta/std/sync/atomic/struct.AtomicIsize.html#method.compare_and_swap), there is no chance that `try_pop` spuriously fails (`Abort`).

`try_pop` may lose the race only if there is only one element.  But if it is the case, a stealer should already have taken the element (by the strength of the compare-and-swap), and indeed there is no remaining element.

**Comment by rphmeier** [comment]
Your argument is that `Pop { Success(item), Fail, Empty }` is unnecessary because `Fail` necessarily equals `Empty`?

**Comment by jeehoonkang** [comment]
Yes, either pop succeeds or the queue is empty.  No fail/abort.
