### ISSUE TITLE
Online documentation is out of date

### ISSUE THREAD

**Issue by maximih** [crossbeam-rs/crossbeam#77]
The [online documentation](http://aturon.github.io/crossbeam-doc/crossbeam/) linked from the main repo page seem to be out of data as it's missing relatively new features such as `ArcCell`.

FWIW, servo seem to store [up to date `crossbeam` documentation](https://doc.servo.org/crossbeam/).

**Comment by jeehoonkang** [comment]
I suggest that we switch to doc.rs: https://docs.rs/crossbeam/ .  What do you think?

**Comment by aturon** [comment]
@jeehoonkang Yes please.

**Comment by jeehoonkang** [comment]
Oh, #121 already resolved this issue.
