### ISSUE TITLE
Documentation doesn't provide information to make a decision about which Queue to use

### ISSUE THREAD

**Issue by LaylConway** [crossbeam-rs/crossbeam#78]
Crossbeam includes two different queues, but the only information on which one to pick for a purpose is the short bit in SegQueue, which isn't enough to make a decision. It would be useful to have a section similar to the rust docs' collections documentation.

https://doc.rust-lang.org/std/collections/#when-should-you-use-which-collection

**Comment by stjepang** [comment]
I think `SegQueue` is a clear win over `MsQueue`, except if the size of messages is really large. Then `MsQueue` might scale better. But it would be good to support that theory with benchmarks.

**Comment by stjepang** [comment]
`MsQueue` has been removed so now the choice of queues should be clear.
