### ISSUE TITLE
Panic from scoped threads is returned only when panic != "abort"

### ISSUE THREAD

**Issue by cjordan** [crossbeam-rs/crossbeam#792]
Hi!

I spent a few hours scratching my head yesterday trying to get panics propagated from my `crossbeam_utils::thread::scope`'d threads; it turns out that I had:

```toml
[profile.release]
panic = "abort"
```

in my Cargo.toml.  The [docs](https://docs.rs/crossbeam-utils/latest/crossbeam_utils/thread/fn.scope.html) don't make any mention of this.  I'm happy to make a PR to include this extra bit of information in the docs, but I just wanted to check that this information was welcome.  Happy to field questions.

**Comment by taiki-e** [comment]
I would accept a PR to improve documentation.
