### ISSUE TITLE
AtomicCell for struct's those size is not the power of two

### ISSUE THREAD

**Issue by feelingnothing** [crossbeam-rs/crossbeam#830]
Is it possible to use AtomicCell for struct where underlying atomic type is rounded up to the nearest power of two? For example this would use `AtomicU32`
```rust
struct Foo {
    foo: u16,
    bar: u8,
}
```
This would use `AtomicU64`
```
struct Foo {
    foo: u16,
    bar: u8,
    bar1: u8,
    bar2: u8,
}
```
I don't know the internal workings of `AtomicCell`, but I think if this is possible, the usage cases will increase

**Comment by fprasx** [comment]
You can use `AtomicCell`, but it won't be lock-free.

**Comment by taiki-e** [comment]
One of the conditions for `AtomicCell<T>` to use the atomic type is that `T` has at least the same alignment as the size.

So you can use the `repr` attribute to adjust the alignment.

```rs
#[repr(align(4))]
struct Foo {
    foo: u16,
    bar: u8,
    _padding: u8,
}
```
