### ISSUE TITLE
Race condition when working with a disconnected channel

### ISSUE THREAD

**Issue by alygin** [crossbeam-rs/crossbeam#838]
At the moment, the following piece of code contains a race condition if the spawned thread drops the sender before the receiver blocks on `recv()` (thread sanitizer catches it):

```rust
fn race() {
    static mut V: u32 = 0;
    let (s, r) = bounded::<i32>(10);
    let t = thread::spawn(move || {
        unsafe { V = 1 }; // (A)
        drop(s);
    });
    let _ = r.recv().unwrap_err();
    unsafe { V = 2 } // (B)
    t.join().unwrap();
}
```

The race is only present when using the `Array` or `List` flavor, while `Zero` works fine here. It looks like the reason is that such relaxed loads:

https://github.com/crossbeam-rs/crossbeam/blob/80224bcfb194066a5218b7415cbad16505e5ed34/crossbeam-channel/src/flavors/array.rs#L276-L277

provide no acquire semantics, thus the main thread might not see effect of (A).

The same problem with sending to a disconnected channel.

In earlier versions this was a `SeqCst` load, but then [it was optimized](https://github.com/crossbeam-rs/crossbeam/commit/7d3f7f05e7dbd83720fc7d4e9308a33b9aeead92#diff-b21bf9cfd25f5671c4003684497224ee113851cf7d2448ba4e57839a6421281aR309-R310) and lost its synchronization property, hence (A) is not guaranteed to happen-before (B).

To me it looks like a bug because channels are usually treated as synchronization objects: `std::sync::mpsc` is presented this way [in Rust Doc](https://doc.rust-lang.org/std/sync/index.html) (though mpsc::channel has the same flaw), Go guarantees such synchronization ([here's the same test for Go channels](https://github.com/golang/go/blob/0a1a092c4b56a1d4033372fbd07924dad8cbb50b/src/runtime/race/testdata/chan_test.go#L120-L130), it passes thread sanitizer checks).

But maybe this was a conscious choice to sacrifice synchronization for performance in such cases?

**Comment by alygin** [comment]
I've ported some tests from Go, both [miri](https://github.com/crossbeam-rs/crossbeam/runs/6545613291?check_suite_focus=true) and [tsan](https://github.com/crossbeam-rs/crossbeam/runs/6545613387?check_suite_focus=true) detect races.

**Comment by kprotty** [comment]
> In earlier versions this was a SeqCst load, but then [it was optimized](https://github.com/crossbeam-rs/crossbeam/commit/7d3f7f05e7dbd83720fc7d4e9308a33b9aeead92#diff-b21bf9cfd25f5671c4003684497224ee113851cf7d2448ba4e57839a6421281aR309-R310) and lost its synchronization property, hence (A) is not guaranteed to happen-before (B).

As long as there's a Release operation on `tail` in the drop after (A) (I assume [here from disconnect](https://github.com/crossbeam-rs/crossbeam/blob/80224bcfb194066a5218b7415cbad16505e5ed34/crossbeam-channel/src/flavors/array.rs#L480)), it should be guaranteed to happen-before (B) due to [Atomic-fence synchronization](Atomic-fence_synchronization). 

This seems more like an issue with [TSAN not detecting fences properly](https://github.com/google/sanitizers/issues/1415); something which even the Rust stdlib [specializes for](https://github.com/rust-lang/rust/blob/e209e85e39b4851c3ec122a45ddeabe318b2d522/library/alloc/src/sync.rs#L52-L67).

**Comment by ibraheemdev** [comment]
A `SeqCst` fence followed by a `Relaxed` load provides the necessary synchronization, this is likely a false positive due to [tsan's lack of support for fences](https://github.com/google/sanitizers/issues/1352).

**Comment by alygin** [comment]
@kpotty, thanks!

**Comment by alygin** [comment]
BTW, it's not only TSAN. Miri also detects data race here.

**Comment by alygin** [comment]
@kprotty, following [your comment](https://github.com/rust-lang/miri/issues/2192#issuecomment-1146838335) in the related miri issue:

> After some thought, the crossbeam code is fine to race as drop() isn't necessarily a synchronization point (which the test case was trying to use as such).

I agree that the `drop()` is not expected to be a sync point per se. But the test is not about dropping, it's about disconnecting, though technically they are the same in this case.

My initial concern was that on disconnection, the receiving side awakes but isn't guaranteed to see effects of the memory changes made by the sending side before disconnecting. This may be an unexpected behavior. For instance, channels in Go provide such synchronization on purpose.

The question is should crossbeam channels guarantee the synchronization on _disconnection_ or not? For the Array flavor it can be easily achieved without performance degradation (just by swapping the fence and the load, or even by moving the fence deeper to the `return true`-branch). I'm not sure about the List flavor, didn't look into it yet. Zero is already ok.

@taiki-e, @kprotty, what do you think?

**Comment by kprotty** [comment]
IMO, a channel should only ensure synchronization for the data sent and retrieved through the channel's API. Relying on the channel to create happens-before edges with data external to it (disconnect included, as it's a state observation not a data transfer) feels like unspecified behavior and is better guaranteed through explicit/separate synchronization.

**Comment by alygin** [comment]
@RalfJung, actually, channels work as you described. But there's a more subtle case:

What if the receiver gets to the `recv()` call when the channel has already been closed? The receiver won't wait, it won't receive any message, it'll just continue doing its work. In [the example I provided](https://github.com/crossbeam-rs/crossbeam/issues/838#issue-1244333422), it'll happen if the spawned thread finishes before the main thread calls `recv()`.

Should we guarantee that the main thread sees the effect of (A)? I think we should, because that makes reasoning about possible execution paths easier and removes data race. It can be implemented without performance penalty. At least for the `Array` flavour it can be implemented by fixin the flaw in the current synchronization approach (the relaxed load is sequenced after the fence).

**Comment by RalfJung** [comment]
> it won't receive any message

It implicitly receives the message that the channel has been closed, doesn't it? It doesn't matter whether it actually had to wait or not, the `recv` has to "see" that the channel was closed by doing a load, and I would expect that so sync-with the thread that did the closing.

> Should we guarantee that the main thread sees the effect of (A)?

In my opinion, definitely yes. We can only get to B if A already happened, so the happens-before edge should be established.
