### ISSUE TITLE
Error: could not compile `crossbeam-epoch`

### ISSUE THREAD

**Issue by bubu59** [crossbeam-rs/crossbeam#848]
Ran anchor build and the following error shows up. Is there anything I can do to fix it?  
I have tried running rustfilt as well but it does not seem to help demangle the error.. 
![image](https://user-images.githubusercontent.com/74093051/172551311-c9789f0d-20f0-4b39-8ebe-b8ee65c3428a.png)

**Comment by taiki-e** [comment]
I am not familiar with bpf target, but the error message seems to refer to allocating huge objects on the stack.
Reducing the size of the Bag, as in [this patch](https://github.com/crossbeam-rs/crossbeam/compare/master...taiki-e:bpf), might alleviate the problem.

**Comment by bubu59** [comment]
Thanks for replying! 
ummm, what do you mean reduce the size of the bag?

**Comment by taiki-e** [comment]
I meant reducing the size of [this relatively large struct](https://github.com/crossbeam-rs/crossbeam/blob/657eef1d4e179b5805557f47296bdd92dabb4015/crossbeam-epoch/src/internal.rs#L64), which is named "Bag".
The size of that struct can be adjusted by changing the MAX_OBJECTS constant, as in the patch I linked to.

**Comment by taiki-e** [comment]
You can use [the patch section](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html?highlight=patch#the-patch-section) of Cargo.toml to override dependencies.

**Comment by bubu59** [comment]
ooh.. wow!! ok! this is the first time for me! will give it a shot! thanks!

**Comment by bubu59** [comment]
![image](https://user-images.githubusercontent.com/74093051/173179206-22179900-6a8b-421f-be5b-e14004d810fd.png)
Hello... I have tried patching the source code but am facing this new error code above.. any ideas on how to resolve this?

**Comment by taiki-e** [comment]
I think you need to add `crossbeam-epoch = { ... }` to the patch section, not `crossbeam = { ... }`.

**Comment by bubu59** [comment]
oh yes! that works! but now when I made the changes to the bag size, 
![image](https://user-images.githubusercontent.com/74093051/173180239-9083d770-f13f-4b2d-a100-6495dedaa0e4.png)
and deleted 2 of elements of the array to match the bag size 
![image](https://user-images.githubusercontent.com/74093051/173180285-8ca9fab2-30f9-4b6e-b37a-20ae03f1ba50.png)
it somehow isn't registering the changes which I have alr pushed and committed to my remote github repo..
![image](https://user-images.githubusercontent.com/74093051/173180312-83afae64-82d9-4323-8434-ee7ad9fbadad.png)

Any idea why this might be the case ?

**Comment by taiki-e** [comment]
The changes seem to have been applied properly, but you probably need to reduce the `Deferred::new(no_op_func),`s to match the number of `MAX_OBJECTS`.

**Comment by bubu59** [comment]
![image](https://user-images.githubusercontent.com/74093051/173195942-2d3e3315-7219-465c-aa46-05d74a303862.png)
That's what I did alr but still having the error... its like the compiler is not picking out the change... 
![image](https://user-images.githubusercontent.com/74093051/173195764-1699eebc-e83a-4d31-b591-5b3046a01520.png)
The image above is the change I have made by deleting 2 `Deferred::new(no_op_func),s` to match the number of `MAX_OBJECTS` which I set to `60`. 
![image](https://user-images.githubusercontent.com/74093051/173195911-93bf5d67-c270-42c4-85b0-08d3dc7d0e0c.png)
Compared to the original which has an extra 2 `Deferred::new(no_op_func),s`

**Comment by taiki-e** [comment]
> its like the compiler is not picking out the change...

Running `cargo update` may fix it.

**Comment by bubu59** [comment]
yeap that works...

**Comment by bubu59** [comment]
![image](https://user-images.githubusercontent.com/74093051/173196590-bbb66057-36bb-47ac-b778-291a659476ed.png)
but now its still throwing the same error but without the "exceeding stake size limit issue" ... I have alr reduced `MAX_OBJECT` to 40...

**Comment by taiki-e** [comment]
I guess if it is larger than 1024 bytes, it will be rounded up to 2048 bytes. Try reducing it to 30 as in my patch mentioned above.

That said, I'm not familiar with this target, so I'm not sure if this is the right solution. I would suggest you ask the maintainer or the community of this target (`bpfel-unknown-unknown` is a custom target and I believe there is a project that provides its definition). I wonder if there is a way to increase the stack size...

**Comment by bubu59** [comment]
![image](https://user-images.githubusercontent.com/74093051/173222796-bcdfab5a-4aba-4275-8c13-52fe23da316e.png)
still no luck... sigh... the only time weird is that every time I run anchor build, it always fails at `compiling spin v0.9.3`....

**Comment by taiki-e** [comment]
This seems to be an issue specific to the custom target and not one that can be well handled on our end, so I would suggest you ask the maintainer or community of this target.
