### ISSUE TITLE
Is Atomic suitable for worst-case data structures?

### ISSUE THREAD

**Issue by elidupree** [crossbeam-rs/crossbeam#89]
I'm trying to write some concurrent data structures for a real-time computing project (specifically, a game library). I'm looking at using Atomic for it, but I can't figure out whether the garbage collection is tolerable. (I took a couple of dives into the code, but I didn't figure out whether a thread could ever have to do a lot of garbage collection at once).

What guarantees does crossbeam have for this? Obviously, dropping an Atomic can't be _guaranteed_ to be a worst-case operation because the contained type could have a costly Drop implementation itself. But it could give guarantees conditional on the Drop implementations of the contained types. Does it? If not, could be made to do so?

**Comment by schets** [comment]
The epoch collector isn't hard real time (bounded worst case performance), but it's almost certainly suitable for something soft-realtime like a game. The amount of collection that a thread will do is more like 30-60 objects at a time. If the thread can give up being hard real-time to make the malloc calls to create/destroy the atomic, it's probably going to be fine with the extremely minor collections that crossbeam does.

I started work to add incremental collection capability and more stuff for real-time support but never really finished it. It's not too complicated, just the ability to set scopes for where crossbeam won't collect in that thread or where the amount of collection is limited.

**Comment by elidupree** [comment]
Thanks for the reply! Sounds like it can go ahead and use it. If I detect any cases where it's a problem in practice, I may come back and see if I can add that incremental collection feature myself :-)

**Comment by schets** [comment]
There's a catch I forgot. Currently, it's possible for the collector to kick in on operations that don't actually free anything. So if you have a situation like

``` rust
// not-hard-realtime
crossbeam_deleting_op();
crossbeam_deleting_op();
crossbeam_deleting_op();

//hard-realtime, no allocations
{
    // Might end up calling free to clean up previous ops if the epoch advances here
    crossbeam_read_only_op();
}
```
you would need to avoid crossbeam or wait for the feature to disable collection in some areas. One of the features I was going to add let you outright disable collection in a scope which sounds like it would help a lot for this.

**Comment by stjepang** [comment]
We've got incremental collection in `crossbeam-epoch` now. Closing.

Perhaps it might be worth opening an issue for more advanced features like disabling collection in a scope or tuning the GC's settings.
