### ISSUE TITLE
How to use CrossBeam-Channel in Tokio?

### ISSUE THREAD

**Issue by zhuxiujia** [crossbeam-rs/crossbeam#896]
How to use CrossBeam-Channel in Tokio?

just like ``` flume``` can use  ``` async ``` features to send data between threads and Tokio coroutines

**Comment by taiki-e** [comment]
crossbeam-channel does not support async send/recv.

In async context consider using [async-channel](https://crates.io/crates/async-channel), which is created by the same author (Stjepan Glavina) and uses the same algorithm.

See also https://github.com/crossbeam-rs/crossbeam/issues/501#issuecomment-828354183.
