### ISSUE TITLE
crossbeam-skiplist crate does not work

### ISSUE THREAD

**Issue by power1628** [crossbeam-rs/crossbeam#898]
As the [document](https://github.com/crossbeam-rs/crossbeam/blob/23b10f2b737b6b6b66f5ca224cab2568350940b0/crossbeam-skiplist/README.md) noted
>Usage
> Add this to your Cargo.toml:
> [dependencies]
> crossbeam-skiplist = "0.1"

But `crossbeam-skiplist = "0.1"` in Cargo.toml does not work,
```
error: failed to select a version for the requirement `crossbeam-skiplist = "^0.1"`
candidate versions found which didn't match: 0.0.0
```

**Comment by taiki-e** [comment]
The release is pending in https://github.com/crossbeam-rs/crossbeam/pull/888. Until it is merged, you can use git dependencies.
