### ISSUE TITLE
atomic_cell::is_lock_free test fails on armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by decathorpe** [crossbeam-rs/crossbeam#918]
Building crossbeam-utils 0.8.12 on Fedora Linux, I get a new test failure on 32-bit ARM:

```
---- is_lock_free stdout ----
thread 'is_lock_free' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`', tests/atomic_cell.rs:36:5
```

According to the line numbers, the assertion that fails is this one:

```
    // Sizes of both types must be equal, and the alignment of `u64` must be greater or equal than
    // that of `AtomicU64`. In i686-unknown-linux-gnu, the alignment of `u64` is `4` and alignment
    // of `AtomicU64` is `8`, so `AtomicCell<u64>` is not lock-free.
    assert_eq!(
        AtomicCell::<u64>::is_lock_free(),
        cfg!(not(crossbeam_no_atomic_64))
            && cfg!(any(
                target_pointer_width = "64",
                target_pointer_width = "128"
            ))
    );
```

Looks like the assumptions made in this test aren't correct on 32-bit ARM?

**Comment by taiki-e** [comment]
> Looks like the assumptions made in this test aren't correct on 32-bit ARM?

yeah, arm's 64-bit integers have 8-byte alignment. the following should be correct.

```diff
-             && cfg!(any(
-                 target_pointer_width = "64",
-                 target_pointer_width = "128"
-             ))
+             && std::mem::align_of::<u64>() == 8
```

**Comment by decathorpe** [comment]
Which version of crossbeam-utils is supposed to ship the fix for this issue?
I just tried again with 0.8.14, and the issue is still there.

**Comment by decathorpe** [comment]
Ah, I didn't realize that "master" is no longer for the 0.8 series of releases. Sorry about the noise, then :)
