### ISSUE TITLE
`Scope::defer` closure runs before previously-spawned threads are joined

### ISSUE THREAD

**Issue by mikeyhew** [crossbeam-rs/crossbeam#92]
If you call `scope.defer` **after** threads are spawned, the code that you pass to `scope.defer` is sometimes run before the threads are finished. The problem goes away if the call to `scope.defer` happens before all calls to `scope.spawn`.

```
extern crate crossbeam;

fn main() {
    crossbeam::scope(|scope| {
      for _ in 0..4 {
        scope.spawn(|| {
          println!("Hello from a thread!");
        });
      }
      scope.defer(|| {
        println!("This should be at the end.");
      });
    });
}
```

Example output (this varies due to race conditions):

```
Hello from a thread!
Hello from a thread!
Hello from a thread!
This should be at the end.
Hello from a thread!
```

**Comment by mikeyhew** [comment]
I did some digging in `scoped.rs` and this is what I found:

- A `Scope` has a property called `dtors`, essentially a linked-list of boxed closures that run after the closure passed to `crossbeam::scope` is executed. When you call `scope.defer`, it prepends the passed-in closure to that linked-list.
- When you call `scope.spawn`, a new `dtor` is prepended to the linked list that joins on the newly-spawned thread.
- If all calls to `scope.defer` occur before all calls to `scope.spawn`, then the dtors that join on threads will be first in the list, and all the threads will be joined before the deferred callbacks run, and all is good. If, however, a call to `defer` is made after the threads are spawned, it will be at the start of the linked-list and will run before threads are joined.

The obvious fix that I can think of is to use a separate data structure to keep track of the threads that are spawned, and join them all before running the `defer` callbacks.

**Comment by jeehoonkang** [comment]
I implemented a PR that (accidentally) resolved this issue https://github.com/crossbeam-rs/crossbeam-utils/pull/7.

**Comment by stjepang** [comment]
I think this is an issue we should fix properly.

**Comment by stjepang** [comment]
We've recently removed `defer` so this issue is not relevant anymore. Closing.
