### ISSUE TITLE
can you please cut a point release with PR #922 included?

### ISSUE THREAD

**Issue by stefson** [crossbeam-rs/crossbeam#928]
hey everyone, 

PR #922 will most likely fix a major annoyance, where no rustc with a custom vendor target is able to compile crossbeam. librsvg makes use of crossbeam in their rust port, which is how I noticed this issue. 

so, can you please push out a point release with the fix included? 

thank you

**Comment by taiki-e** [comment]
Published in crossbeam-utils 0.8.13, crossbeam-queue 0.3.7, and crossbeam-epoch 0.9.12.
