### ISSUE TITLE
Handling all Rust targets.

### ISSUE THREAD

**Issue by MediosZ** [crossbeam-rs/crossbeam#931]
I notice that in [this commit](https://github.com/crossbeam-rs/crossbeam/commit/e78e511e30031785253f767caf37e7efa0d08191), we try to replace vendor in targets. But it presumes that all targets are triplets, which doesn't hold for some targets like `wasm32-wasi` and `x86_64-fuchsia`. This causes problems when [compiling crossbeam for these targets](https://github.com/second-state/microservice-rust-mysql/issues/7).

I can fix this if needed or maybe there are better solutions.

**Comment by taiki-e** [comment]
Thanks for the report! I yanked the versions affected by this bug.

I believe the ideal solution here is to use `cfg_target_has_atomic` on Rust 1.60+ like my [portable-atomic](https://github.com/taiki-e/portable-atomic) crate does.

**Comment by taiki-e** [comment]
Fixed in crossbeam-utils 0.8.14, crossbeam-queue 0.3.8, and crossbeam-epoch 0.9.13. (#932)
