### ISSUE TITLE
SegQueue misses first element on pop

### ISSUE THREAD

**Issue by shamatar** [crossbeam-rs/crossbeam#951]
I'm using SegQueue to for a task of single producer - single consumer, but in some cases I see that the first element that was pushed in one thread is never popped in another thread. All the next elements are properly passing (popped after being pushed). 

I was able to catch it only because elements in the queue form a dependency graph, and if first element is missing then all other dependencies can never be resolved, that leads to infinite loop.

**Comment by taiki-e** [comment]
Is there code that can reproduce this? (Do you mean that cases like [this test](https://github.com/crossbeam-rs/crossbeam/blob/5519aeb5c2156c5aff9a88d41dcfbcd838e9a1ea/crossbeam-queue/tests/seg_queue.rs#L56) don't work?)
