### ISSUE TITLE
Semantic one-shot channel

### ISSUE THREAD

**Issue by tisonkun** [crossbeam-rs/crossbeam#985]
Different from https://github.com/crossbeam-rs/crossbeam/issues/199, a semantic one-shot channel may help in reasoning.

That said, `bounded(1)` doesn't mean the channel will handle only one event all the time, but it can buffer at most one event.

A semantic one-shot channel is like a CountDownLaunch with `count=1`, which means only one event can be delivered and the following will be rejected with an error.

I don't find an implementation in crossbeam-channel. Thus, I file this issue to see if it's a valid suggestion or we can implement it with current structs.

**Comment by taiki-e** [comment]
What is the actual purpose of this?

If the purpose is to restrict the API, you might be able to do this just by creating a wrapper type.

If the purpose is performance, it is not clear how large the actual performance benefit is, as I felt the single-capacity optimized variant I tried in https://github.com/crossbeam-rs/crossbeam/issues/199 was similar to the one used in tokio::sync::oneshot.

**Comment by tisonkun** [comment]
> If the purpose is to restrict the API, you might be able to do this just by creating a wrapper type.

That sounds reasonable...Do you have a demo wrapper for such usage?

**Comment by tisonkun** [comment]
I know that I can wrap a `OneShotSender` that has a `fn send(self, ...)` now.

Thanks for your well-written library for use!
