### ISSUE TITLE
Publish new `crossbeam-epoch` with updated `memoffset`

### ISSUE THREAD

**Issue by poliorcetics** [crossbeam-rs/crossbeam#986]
I see `memoffset` was updated to 0.9 in `crossbeam-epoch` some time ago, could a new release be done with this included ?

I don't think `memoffset` is part of the public API of the crate (the only use in is `crossbeam-epoch/src/internal.rs`, with a local `use ...`) so this could be a patch release

If more work is necessary before such a release, I can try to help

**Comment by taiki-e** [comment]
Published crossbeam-epoch 0.9.15.

**Comment by poliorcetics** [comment]
Thank you for the quick response!
